/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import dao.CongNhanDao;
import dao.PhanCongCNDao;
import dao.SanPhamDao;
import entity.PhanDoan;
import entity.SanPham;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import dao.PhanDoanDao;
import entity.CongNhan;
import entity.PhanCong;
import java.awt.PopupMenu;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import static org.apache.commons.math3.fitting.leastsquares.LeastSquaresFactory.model;

/**
 *
 * @author duy19
 */
public final class FrmPhanCongCongNhan extends javax.swing.JPanel {

    private DefaultTableModel model, model1;
    private FrmChonCongNhan frmChonCN;
//    private TrangChu_GUI trangChu;

    /**
     * Creates new form FrmPhanCongCN
     */
    public FrmPhanCongCongNhan() throws Exception {
        initComponents();
        loadDataToTale();
        initTable();
        loadDataToTablePCCN();
        Calendar currentDate = Calendar.getInstance();
        currentDate.add(Calendar.MINUTE, 10);
        txtTrangthai.setText("Chưa hoàn thành");
        txtTrangthai.setEnabled(false);
        jDateNgayPhanCong.setDate(currentDate.getTime());
        //jDateNgayPhanCong.setEnabled(false);
        txtHoTenCN.setEnabled(false);
        txtMaCongNhan.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTieuDe1 = new javax.swing.JLabel();
        ThongTinPC = new javax.swing.JPanel();
        lblMaSanPham = new javax.swing.JLabel();
        txtMaPhanCong = new javax.swing.JTextField();
        lblMaSanPham1 = new javax.swing.JLabel();
        lblMaSanPham2 = new javax.swing.JLabel();
        txtMaPhanDoan = new javax.swing.JTextField();
        lblMaSanPham3 = new javax.swing.JLabel();
        txtMaCongNhan = new javax.swing.JTextField();
        lblMaSanPham4 = new javax.swing.JLabel();
        txtSLCanLam = new javax.swing.JTextField();
        lblMaSanPham5 = new javax.swing.JLabel();
        lblMaSanPham6 = new javax.swing.JLabel();
        jDateNgayPhanCong = new com.toedter.calendar.JDateChooser();
        txtTrangthai = new javax.swing.JTextField();
        txtTenPhanDoan = new javax.swing.JTextField();
        lblMaSanPham7 = new javax.swing.JLabel();
        jDateNgayHoanThanh = new com.toedter.calendar.JDateChooser();
        lblMaSanPham8 = new javax.swing.JLabel();
        txtHoTenCN = new javax.swing.JTextField();
        btnChonCN = new javax.swing.JButton();
        pnlNutChucNang = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXoaPhanDoan = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnXoaRong = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblDSPhanCong = new javax.swing.JTable();
        tblDSSanPham = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDSSP = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblDSPhanDoan = new javax.swing.JTable();

        lblTieuDe1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTieuDe1.setForeground(new java.awt.Color(51, 0, 255));
        lblTieuDe1.setText("PHÂN CÔNG CÔNG NHÂN");

        lblMaSanPham.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMaSanPham.setText("Mã phân công:");

        txtMaPhanCong.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMaPhanCongFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMaPhanCongFocusLost(evt);
            }
        });

        lblMaSanPham1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMaSanPham1.setText("Ngày phân công");

        lblMaSanPham2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMaSanPham2.setText("Mã phân đoạn:");

        txtMaPhanDoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaPhanDoanActionPerformed(evt);
            }
        });

        lblMaSanPham3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMaSanPham3.setText("Mã công nhân:");

        txtMaCongNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaCongNhanActionPerformed(evt);
            }
        });

        lblMaSanPham4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMaSanPham4.setText("Số lượng cần làm");

        txtSLCanLam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSLCanLamActionPerformed(evt);
            }
        });

        lblMaSanPham5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMaSanPham5.setText("Tên phân đoạn:");

        lblMaSanPham6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMaSanPham6.setText("Trạng thái");

        jDateNgayPhanCong.setDateFormatString("dd/MM/yyyy");

        txtTrangthai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTrangthaiActionPerformed(evt);
            }
        });

        txtTenPhanDoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenPhanDoanActionPerformed(evt);
            }
        });

        lblMaSanPham7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMaSanPham7.setText("Ngày hoàn thành");

        jDateNgayHoanThanh.setDateFormatString("dd/MM/yyyy");

        lblMaSanPham8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMaSanPham8.setText("Tên công nhân");

        txtHoTenCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoTenCNActionPerformed(evt);
            }
        });

        btnChonCN.setBackground(new java.awt.Color(204, 255, 204));
        btnChonCN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnChonCN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icon-tìmkiemNV.png"))); // NOI18N
        btnChonCN.setText("Chọn công nhân");
        btnChonCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonCNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ThongTinPCLayout = new javax.swing.GroupLayout(ThongTinPC);
        ThongTinPC.setLayout(ThongTinPCLayout);
        ThongTinPCLayout.setHorizontalGroup(
            ThongTinPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThongTinPCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ThongTinPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ThongTinPCLayout.createSequentialGroup()
                        .addGroup(ThongTinPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ThongTinPCLayout.createSequentialGroup()
                                .addComponent(lblMaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaPhanCong, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                            .addGroup(ThongTinPCLayout.createSequentialGroup()
                                .addComponent(lblMaSanPham2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaPhanDoan)))
                        .addGap(35, 35, 35)
                        .addGroup(ThongTinPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaSanPham5)
                            .addComponent(lblMaSanPham1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaSanPham7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ThongTinPCLayout.createSequentialGroup()
                        .addGroup(ThongTinPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ThongTinPCLayout.createSequentialGroup()
                                .addGroup(ThongTinPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(ThongTinPCLayout.createSequentialGroup()
                                        .addComponent(lblMaSanPham3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtMaCongNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ThongTinPCLayout.createSequentialGroup()
                                        .addComponent(lblMaSanPham8, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtHoTenCN, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(44, 44, 44)
                                .addComponent(lblMaSanPham6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblMaSanPham4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ThongTinPCLayout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(txtSLCanLam, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(ThongTinPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTrangthai)
                    .addComponent(txtTenPhanDoan)
                    .addComponent(jDateNgayHoanThanh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateNgayPhanCong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnChonCN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13))
        );
        ThongTinPCLayout.setVerticalGroup(
            ThongTinPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongTinPCLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(ThongTinPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ThongTinPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMaPhanCong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblMaSanPham1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateNgayPhanCong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ThongTinPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ThongTinPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMaSanPham2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMaPhanDoan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblMaSanPham7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateNgayHoanThanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ThongTinPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ThongTinPCLayout.createSequentialGroup()
                        .addGroup(ThongTinPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaSanPham3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaCongNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addGroup(ThongTinPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaSanPham4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSLCanLam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ThongTinPCLayout.createSequentialGroup()
                        .addGroup(ThongTinPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaSanPham5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenPhanDoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ThongTinPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ThongTinPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblMaSanPham8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtHoTenCN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ThongTinPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtTrangthai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblMaSanPham6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnChonCN, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(21, 21, 21))
        );

        btnThem.setBackground(new java.awt.Color(102, 255, 102));
        btnThem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/them.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setMargin(new java.awt.Insets(2, 2, 3, 2));
        btnThem.setMaximumSize(new java.awt.Dimension(115, 37));
        btnThem.setMinimumSize(new java.awt.Dimension(115, 37));
        btnThem.setPreferredSize(new java.awt.Dimension(125, 37));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoaPhanDoan.setBackground(new java.awt.Color(255, 102, 102));
        btnXoaPhanDoan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXoaPhanDoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icon-xoachamcong.png"))); // NOI18N
        btnXoaPhanDoan.setText("Xóa");
        btnXoaPhanDoan.setMargin(new java.awt.Insets(2, 2, 3, 2));
        btnXoaPhanDoan.setPreferredSize(new java.awt.Dimension(125, 23));
        btnXoaPhanDoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaPhanDoanActionPerformed(evt);
            }
        });

        btnLamMoi.setBackground(new java.awt.Color(255, 255, 153));
        btnLamMoi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icon-CapNhat.png"))); // NOI18N
        btnLamMoi.setText("Sửa");
        btnLamMoi.setMargin(new java.awt.Insets(2, 2, 3, 2));
        btnLamMoi.setPreferredSize(new java.awt.Dimension(125, 22));
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnXoaRong.setBackground(new java.awt.Color(102, 153, 255));
        btnXoaRong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXoaRong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icon-LamMoi.png"))); // NOI18N
        btnXoaRong.setText("Làm mới");
        btnXoaRong.setMargin(new java.awt.Insets(2, 0, 3, 0));
        btnXoaRong.setPreferredSize(new java.awt.Dimension(125, 22));
        btnXoaRong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaRongActionPerformed(evt);
            }
        });

        btnThoat.setBackground(new java.awt.Color(204, 204, 204));
        btnThoat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icon-thoat.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.setMargin(new java.awt.Insets(2, 2, 3, 2));
        btnThoat.setPreferredSize(new java.awt.Dimension(125, 23));
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNutChucNangLayout = new javax.swing.GroupLayout(pnlNutChucNang);
        pnlNutChucNang.setLayout(pnlNutChucNangLayout);
        pnlNutChucNangLayout.setHorizontalGroup(
            pnlNutChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNutChucNangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnXoaPhanDoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnXoaRong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlNutChucNangLayout.setVerticalGroup(
            pnlNutChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNutChucNangLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnlNutChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaPhanDoan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaRong, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách phân công", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        tblDSPhanCong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDSPhanCong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSPhanCongMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblDSPhanCong);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190))
        );

        tblDSSanPham.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        tblDSSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDSSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSSPMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblDSSP);

        javax.swing.GroupLayout tblDSSanPhamLayout = new javax.swing.GroupLayout(tblDSSanPham);
        tblDSSanPham.setLayout(tblDSSanPhamLayout);
        tblDSSanPhamLayout.setHorizontalGroup(
            tblDSSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tblDSSanPhamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                .addContainerGap())
        );
        tblDSSanPhamLayout.setVerticalGroup(
            tblDSSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tblDSSanPhamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách phân đoạn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        tblDSPhanDoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDSPhanDoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSPhanDoanMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblDSPhanDoan);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(pnlNutChucNang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tblDSSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ThongTinPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 51, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(631, 631, 631)
                .addComponent(lblTieuDe1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTieuDe1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tblDSSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ThongTinPC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pnlNutChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void loadDataToTale() throws Exception {
        SanPhamDao sanPhamDAO = new SanPhamDao();
        List<SanPham> sanPhams = sanPhamDAO.getAllSanPham();
        model = new DefaultTableModel();
        model.addColumn("Mã sản phẩm");
        model.addColumn("Tên sản phẩm");
        model.addColumn("Loại sản phẩm");
        model.addColumn("Màu sắc");

        for (SanPham sanPham : sanPhams) {
            model.addRow(new Object[]{
                sanPham.getMaSanPham(),
                sanPham.getTenSanPham(),
                sanPham.getLoaiSanPham(),
                sanPham.getMauSac()
            });
        }
        tblDSSP.setModel(model);
    }

    public static void xoaRong() {
        txtHoTenCN.setText("");
        txtMaCongNhan.setText("");
    }

    public static void setMavaTen(CongNhan cn) {
        txtHoTenCN.setText(cn.getTenCongNhan());
        txtMaCongNhan.setText(cn.getMaCongNhan());
    }


    private void tblDSSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSSPMouseClicked
        // TODO add your handling code here:
        int row = tblDSSP.getSelectedRow();

        PhanDoanDao phanDoanDao = new PhanDoanDao();
        SanPhamDao spDao = new SanPhamDao();
        if (row != -1) {
            try {
                String id = (String) tblDSSP.getValueAt(row, 0);
                String ten = (String) tblDSSP.getValueAt(row, 1);
                List<PhanDoan> list = phanDoanDao.layDSCongDoanTheoMaSP(id);

                if (list.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Không tìm thấy phân đoạn cho sản phẩm này", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    xoaDuLieuTrongBang();
                } else {
                    model1 = new DefaultTableModel();
                    model1.addColumn("Mã phân đoạn");
                    model1.addColumn("Tên phân đoạn");
                    model1.addColumn("Mã sản phẩm");
                    model1.addColumn("Tên sản phẩm");
                    model1.addColumn("Giá phân đoạn");
                    model1.addColumn("Phân đoạn yêu cầu");
                    for (PhanDoan phanDoan : list) {

                        model1.addRow(new Object[]{
                            phanDoan.getMaPhanDoan(),
                            phanDoan.getTenPhanDoan(),
                            phanDoan.getSanPham().getMaSanPham(),
                            ten,
                            phanDoan.getGiaPhanDoan(),
                            phanDoan.getPhanDoanYeuCau()
                        });
                    }
                    tblDSPhanDoan.setModel(model1);

                }
            } catch (Exception ex) {
                Logger.getLogger(FrmPhanCongCongNhan.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_tblDSSPMouseClicked

    private void txtMaPhanDoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaPhanDoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaPhanDoanActionPerformed

    private void txtMaCongNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaCongNhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaCongNhanActionPerformed

    private void txtSLCanLamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSLCanLamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSLCanLamActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        try {
            PhanDoanDao pd_dao = new PhanDoanDao();
            PhanDoan pd = pd_dao.getCDByID(txtMaPhanDoan.getText());
            CongNhanDao cn_dao = new CongNhanDao();
            CongNhan cn = cn_dao.getCNByID(txtMaCongNhan.getText());
            PhanCong pcCN = new PhanCong(txtMaPhanCong.getText(), pd, cn, Integer.parseInt(txtSLCanLam.getText()), jDateNgayPhanCong.getDate(), jDateNgayHoanThanh.getDate(), txtTrangthai.getText());
            System.out.println(pcCN);
            PhanCongCNDao pccn_dao = new PhanCongCNDao();
            boolean n = pccn_dao.themPhanCong(pcCN);
            System.out.println(n);
            //JOptionPane.showMessageDialog(this, "Thêm thành công");
            loadDataToTablePCCN();
        } catch (Exception ex) {
            Logger.getLogger(FrmQuanLyCongNhan.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnThemActionPerformed


    private void tblDSPhanCongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSPhanCongMouseClicked
        // TODO add your handling code here:
        try {
            int row = tblDSPhanCong.getSelectedRow();
            if (row >= 0) {
                String id = (String) tblDSPhanCong.getValueAt(row, 0);
                PhanCongCNDao pccn_Dao = new PhanCongCNDao();
                PhanCong pcCN = pccn_Dao.getPCCNByID(id);
                if (pcCN != null) {
                    txtMaPhanCong.setText(pcCN.getMaPC());
                    txtMaPhanDoan.setText(pcCN.getCongDoan().getMaPhanDoan());
                    txtHoTenCN.setText(pcCN.getCongNhan().getTenCongNhan());
                    txtMaCongNhan.setText(pcCN.getCongNhan().getMaCongNhan());
                    txtSLCanLam.setText(String.valueOf(pcCN.getSoLuongCanLam()));
                    txtTenPhanDoan.setText(pcCN.getCongDoan().getTenPhanDoan());
                    txtTrangthai.setText(pcCN.getTrangThai());
                    jDateNgayHoanThanh.setDate(pcCN.getNgayHoanThanh());
                    jDateNgayPhanCong.setDate(pcCN.getNgayPhanCong());
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_tblDSPhanCongMouseClicked


    private void tblDSPhanDoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSPhanDoanMouseClicked
        // TODO add your handling code here:
        try {
            int row = tblDSPhanDoan.getSelectedRow();
            if (row >= 0) {
                String id = (String) tblDSPhanDoan.getValueAt(row, 0);
                PhanDoanDao pd_dao = new PhanDoanDao();
                PhanDoan pd = pd_dao.getCDByID(id);
                if (pd != null) {

                    txtMaPhanDoan.setText(pd.getMaPhanDoan());
                    txtTenPhanDoan.setText(pd.getTenPhanDoan());

                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tblDSPhanDoanMouseClicked

    private void btnXoaPhanDoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaPhanDoanActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa công nhân này?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            PhanCongCNDao dao = new PhanCongCNDao();
            try {
                dao.xoaPhanCong(txtMaPhanCong.getText());
            } catch (SQLException ex) {
                Logger.getLogger(FrmPhanCongCongNhan.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                loadDataToTablePCCN();
            } catch (Exception ex) {

            }
        }

    }//GEN-LAST:event_btnXoaPhanDoanActionPerformed

    private void txtHoTenCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoTenCNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoTenCNActionPerformed

    private void btnChonCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonCNActionPerformed
        // TODO add your handling code here:
        frmChonCN = new FrmChonCongNhan();
        frmChonCN.setVisible(true);
        frmChonCN.setLocationRelativeTo(this);
        frmChonCN.setAlwaysOnTop(true);

    }//GEN-LAST:event_btnChonCNActionPerformed

    private void btnXoaRongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaRongActionPerformed
        // TODO add your handling code here:
        Calendar currentDate = Calendar.getInstance();
        txtMaPhanCong.setText("");
        txtHoTenCN.setText("");
        txtMaCongNhan.setText("");
        txtMaPhanDoan.setText("");
        txtSLCanLam.setText("");
        txtTenPhanDoan.setText("");
        currentDate.add(Calendar.MINUTE, 10);
        jDateNgayPhanCong.setDate(currentDate.getTime());

    }//GEN-LAST:event_btnXoaRongActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        SwingUtilities.getWindowAncestor(this).dispose();
        this.setVisible(false);
        new TrangChu_GUI().setVisible(true);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void txtTenPhanDoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenPhanDoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenPhanDoanActionPerformed

    private void txtTrangthaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTrangthaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTrangthaiActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        PhanDoanDao pd_dao = new PhanDoanDao();
        PhanDoan pd;
        try {
            pd = pd_dao.getCDByID(txtMaPhanDoan.getText());
            CongNhanDao cn_dao = new CongNhanDao();
            CongNhan cn = cn_dao.getCNByID(txtMaCongNhan.getText());
            PhanCong pcCN = new PhanCong(txtMaPhanCong.getText(), pd, cn, Integer.parseInt(txtSLCanLam.getText()), jDateNgayPhanCong.getDate(), jDateNgayHoanThanh.getDate(), txtTrangthai.getText());
            PhanCongCNDao pccn_Dao = new PhanCongCNDao();
            int option = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắc muốn cập nhật không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.YES_OPTION) {
                try {
                    pccn_Dao.suaPhanCong(pcCN);
                    JOptionPane.showMessageDialog(this, "Cập nhật thành công");
                    loadDataToTablePCCN();
                } catch (Exception ex) {
                    Logger.getLogger(FrmQuanLyCongNhan.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        } catch (Exception ex) {
            Logger.getLogger(FrmPhanCongCongNhan.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void txtMaPhanCongFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaPhanCongFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaPhanCongFocusGained

    private void txtMaPhanCongFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaPhanCongFocusLost
        // TODO add your handling code here:


    }//GEN-LAST:event_txtMaPhanCongFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JPanel ThongTinPC;
    private javax.swing.JButton btnChonCN;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoaPhanDoan;
    private javax.swing.JButton btnXoaRong;
    private com.toedter.calendar.JDateChooser jDateNgayHoanThanh;
    private com.toedter.calendar.JDateChooser jDateNgayPhanCong;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lblMaSanPham;
    private javax.swing.JLabel lblMaSanPham1;
    private javax.swing.JLabel lblMaSanPham2;
    private javax.swing.JLabel lblMaSanPham3;
    private javax.swing.JLabel lblMaSanPham4;
    private javax.swing.JLabel lblMaSanPham5;
    private javax.swing.JLabel lblMaSanPham6;
    private javax.swing.JLabel lblMaSanPham7;
    private javax.swing.JLabel lblMaSanPham8;
    private javax.swing.JLabel lblTieuDe1;
    private javax.swing.JPanel pnlNutChucNang;
    private javax.swing.JTable tblDSPhanCong;
    private javax.swing.JTable tblDSPhanDoan;
    private javax.swing.JTable tblDSSP;
    private javax.swing.JPanel tblDSSanPham;
    private static javax.swing.JTextField txtHoTenCN;
    private static javax.swing.JTextField txtMaCongNhan;
    private javax.swing.JTextField txtMaPhanCong;
    private javax.swing.JTextField txtMaPhanDoan;
    private javax.swing.JTextField txtSLCanLam;
    private javax.swing.JTextField txtTenPhanDoan;
    private javax.swing.JTextField txtTrangthai;
    // End of variables declaration//GEN-END:variables

    private void xoaDuLieuTrongBang() {
        DefaultTableModel model = (DefaultTableModel) tblDSPhanDoan.getModel();
        model.setRowCount(0);
    }

    private void initTable() {
        model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{"Mã phân công", "Mã công đoạn", "Mã công nhân", "Số lượng cần làm", "Ngày phân công",
            "Ngày hoàn thành", "Trạng thái"});
        tblDSPhanCong.setModel(model);
    }

    public void loadDataToTablePCCN() {
        try {
            PhanCongCNDao pccn_dao = new PhanCongCNDao();
            List<PhanCong> list = pccn_dao.getDSPhanCong();
            model.setRowCount(0);
            for (PhanCong pccn : list) {
                {
                    model.addRow(new Object[]{
                        pccn.getMaPC(),
                        pccn.getCongDoan().getMaPhanDoan(),
                        pccn.getCongNhan().getMaCongNhan(),
                        pccn.getSoLuongCanLam(),
                        pccn.getNgayPhanCong(),
                        pccn.getNgayHoanThanh(),
                        pccn.getTrangThai()
                    });
                }
            }
            model.fireTableDataChanged();
        } catch (Exception e) {
        }
    }
}
