/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import dao.NhanVienDao;
import dao.TaiKhoanDao;
import entity.TaiKhoan;
import helper.MaNguoiDung;
import helper.TenNguoiDung;
import java.awt.event.ItemEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author huylauri
 */
public class FrmThayDoiMatKhau extends javax.swing.JPanel {

    private String maNguoiDung = null;
    private NhanVienDao nhanVienDao = new NhanVienDao();
    private TaiKhoanDao taiKhoanDao = new TaiKhoanDao();

    /**
     * Creates new form FrmThayDoiMatKhau
     */
    public FrmThayDoiMatKhau() {
        initComponents();
        TenNguoiDung nguoiDung = new TenNguoiDung();
        MaNguoiDung maNguoiDungHel = new MaNguoiDung();
        String tenNguoiDung = nguoiDung.getTenNguoiDung();
        maNguoiDung = maNguoiDungHel.getMaNguoiDung();
        lblTenNhanVien.setText(tenNguoiDung);

    }

    public boolean kiemTraMatKhau(String password) {
        // Kiểm tra độ dài ít nhất 8 kí tự
        if (password.length() < 8) {
            return false;
        }
        // Kiểm tra chứa ít nhất một chữ hoa
        if (!Pattern.compile("[A-Z]").matcher(password).find()) {
            return false;
        }
        // Kiểm tra chứa ít nhất một chữ số
        if (!Pattern.compile("\\d").matcher(password).find()) {
            return false;
        }
        // Kiểm tra chứa ít nhất một kí tự đặc biệt
        if (!Pattern.compile("[!@#$%^&*()-+=.]").matcher(password).find()) {
            return false;
        }
        return true;
    }

    public void xoaRong() {
        txtMatKhauHienTai.setText("");
        txtMatKhauMoi.setText("");
        txtXacNhanMatKhau.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLeft = new javax.swing.JPanel();
        lblTenNhanVien = new javax.swing.JLabel();
        pnlRight = new javax.swing.JPanel();
        lblTieuDe = new javax.swing.JLabel();
        lblMatKhauHienTai = new javax.swing.JLabel();
        lblMatKhauMoi = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnLuulai = new javax.swing.JButton();
        btnHuyBo = new javax.swing.JButton();
        chkHienThiMatKhau = new javax.swing.JCheckBox();
        txtMatKhauMoi = new javax.swing.JPasswordField();
        txtXacNhanMatKhau = new javax.swing.JPasswordField();
        txtMatKhauHienTai = new javax.swing.JPasswordField();

        pnlLeft.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(51, 102, 255)));

        lblTenNhanVien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTenNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/TaiKhoan.png"))); // NOI18N
        lblTenNhanVien.setText("Tran Quang Huy");
        lblTenNhanVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTenNhanVien.setIconTextGap(8);
        lblTenNhanVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout pnlLeftLayout = new javax.swing.GroupLayout(pnlLeft);
        pnlLeft.setLayout(pnlLeftLayout);
        pnlLeftLayout.setHorizontalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLeftLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(lblTenNhanVien)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        pnlLeftLayout.setVerticalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeftLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlRight.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(0, 0, 0)));

        lblTieuDe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTieuDe.setForeground(new java.awt.Color(51, 0, 255));
        lblTieuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTieuDe.setText("THAY ĐỔI MẬT KHẨU");
        lblTieuDe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblMatKhauHienTai.setText("Mật khẩu hiện tại:");

        lblMatKhauMoi.setText("Mật khẩu mới:");

        jLabel5.setText("Xác nhận mật khẩu:");

        btnLuulai.setBackground(new java.awt.Color(51, 153, 255));
        btnLuulai.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLuulai.setForeground(new java.awt.Color(255, 255, 255));
        btnLuulai.setText("Lưu lại");
        btnLuulai.setMargin(new java.awt.Insets(2, 2, 3, 2));
        btnLuulai.setMaximumSize(new java.awt.Dimension(115, 37));
        btnLuulai.setMinimumSize(new java.awt.Dimension(115, 37));
        btnLuulai.setPreferredSize(new java.awt.Dimension(125, 37));
        btnLuulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuulaiActionPerformed(evt);
            }
        });

        btnHuyBo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHuyBo.setForeground(new java.awt.Color(255, 0, 0));
        btnHuyBo.setText("Huỷ bỏ");
        btnHuyBo.setMargin(new java.awt.Insets(2, 2, 3, 2));
        btnHuyBo.setPreferredSize(new java.awt.Dimension(125, 23));
        btnHuyBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyBoActionPerformed(evt);
            }
        });

        chkHienThiMatKhau.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chkHienThiMatKhau.setText("Hiển thị mật khẩu");
        chkHienThiMatKhau.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkHienThiMatKhauItemStateChanged(evt);
            }
        });
        chkHienThiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkHienThiMatKhauActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRightLayout = new javax.swing.GroupLayout(pnlRight);
        pnlRight.setLayout(pnlRightLayout);
        pnlRightLayout.setHorizontalGroup(
            pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightLayout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(chkHienThiMatKhau)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlRightLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnLuulai, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(btnHuyBo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addComponent(lblMatKhauHienTai, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMatKhauMoi, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTieuDe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMatKhauMoi, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtXacNhanMatKhau)
                    .addComponent(txtMatKhauHienTai))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        pnlRightLayout.setVerticalGroup(
            pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lblTieuDe)
                .addGap(45, 45, 45)
                .addComponent(lblMatKhauHienTai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMatKhauHienTai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lblMatKhauMoi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtXacNhanMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(chkHienThiMatKhau)
                .addGap(45, 45, 45)
                .addGroup(pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLuulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHuyBo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnHuyBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyBoActionPerformed
//      Lấy JTabbedPane chính
        JTabbedPane tabbedPane = (JTabbedPane) SwingUtilities.getAncestorOfClass(JTabbedPane.class, this); 
//      Xác định index của tab hiện tại
        int index = tabbedPane.indexOfComponent(this);
//      Xóa tab hiện tại
        if (index != -1) {
            tabbedPane.removeTabAt(index);
        }
//      Nếu không còn tab nào hiển thị, đặt lại giao diện chính
        if (tabbedPane.getTabCount() == 0) {
            JFrame mainFrame = (JFrame) SwingUtilities.getWindowAncestor(tabbedPane);
            mainFrame.getContentPane().removeAll();
            mainFrame.getContentPane().add(new TrangChu_GUI());
            mainFrame.getContentPane().revalidate();
        }
    }//GEN-LAST:event_btnHuyBoActionPerformed

    private void chkHienThiMatKhauItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkHienThiMatKhauItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            txtMatKhauHienTai.setEchoChar((char) 0);
            txtMatKhauMoi.setEchoChar((char) 0);
            txtXacNhanMatKhau.setEchoChar((char) 0);
        } else {
            txtMatKhauHienTai.setEchoChar('*');
            txtMatKhauMoi.setEchoChar('*');
            txtXacNhanMatKhau.setEchoChar('*');

        }
    }//GEN-LAST:event_chkHienThiMatKhauItemStateChanged

    private void chkHienThiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkHienThiMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkHienThiMatKhauActionPerformed

    private void btnLuulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuulaiActionPerformed
        char[] matKhauHienTai = txtMatKhauHienTai.getPassword();
        char[] maKhauMoi = txtMatKhauMoi.getPassword();
        char[] maKhauXacNhan = txtXacNhanMatKhau.getPassword();
        String matKhauHienTaiString = new String(matKhauHienTai);
        String maKhauMoiString = new String(maKhauMoi);
        String maKhauXacNhanString = new String(maKhauXacNhan);

        System.out.println(maNguoiDung);
        try {
            TaiKhoan taiKhoan = taiKhoanDao.layTaiKhoanTheoMaNV(maNguoiDung);
            if (taiKhoan.getMatKhau().equals(matKhauHienTaiString)) {
                if (kiemTraMatKhau(maKhauMoiString)) {
                    if (maKhauMoiString.equals(maKhauXacNhanString)) {
                        taiKhoanDao.capNhatMatKhau(maKhauMoiString, maNguoiDung);
                        JOptionPane.showMessageDialog(this, "Cập nhật mật khẩu thành công.");
                        xoaRong();
                    } else {
                        JOptionPane.showMessageDialog(this, "Các mật khẩu mới đã nhập không khớp. Hãy thử lại.");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Mật khẩu mới phải ít nhất 8 kí tự, có chứa chữ cái in hoa, số và ký tự đặc biệt!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Mật khẩu hiện tại không đúng!");
            }

        } catch (Exception ex) {
            Logger.getLogger(FrmThayDoiMatKhau.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLuulaiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuyBo;
    private javax.swing.JButton btnLuulai;
    private javax.swing.JCheckBox chkHienThiMatKhau;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblMatKhauHienTai;
    private javax.swing.JLabel lblMatKhauMoi;
    private javax.swing.JLabel lblTenNhanVien;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlRight;
    private javax.swing.JPasswordField txtMatKhauHienTai;
    private javax.swing.JPasswordField txtMatKhauMoi;
    private javax.swing.JPasswordField txtXacNhanMatKhau;
    // End of variables declaration//GEN-END:variables
}
