/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import dao.ChamCongCNDao;
import dao.PhanCongDao;
import entity.ChamCongCN;
import entity.PhanCong;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ChanhkKhongNgu
 */
public class FrmChamCongCN extends javax.swing.JPanel {

    private final ChamCongCNDao chamCongCNDao;

    public FrmChamCongCN() {
        chamCongCNDao = new ChamCongCNDao();
        initComponents();
        loadTableData();
        checkInputData();
    }

    private void setNCC() {
        LocalDate currentDate = LocalDate.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        String formattedDate = currentDate.format(formatter);
        txtNgayChamCong.setText(formattedDate);
        txtHeSoCa.setText("1.2");
    }

    private void checkInputData() {
        txtMaPhanCong.setEnabled(false);
        txtMaCongNhan.setEnabled(false);
        txtNgayChamCong.setEnabled(false);
        txtHeSoCa.setEnabled(false);
        setNCC();
    }

    private void loadTableData() {
        PhanCongDao phanCongDao = new PhanCongDao();
        List<PhanCong> phanCongs = phanCongDao.getAllPhanCong();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Mã phân công");
        model.addColumn("Mã phân đoạn");
        model.addColumn("Mã công nhân");
        model.addColumn("Số lượng cần làm");
        model.addColumn("Ngày phân công");
        model.addColumn("Ngày hoàn thành");
        model.addColumn("Trạng thái");

        for (PhanCong phanCong : phanCongs) {
            model.addRow(new Object[]{
                phanCong.getMaPhanCong(),
                phanCong.getPhanDoan().getMaPhanDoan(),
                phanCong.getCongNhan().getMaCongNhan(),
                phanCong.getSoLuongCanLam(),
                phanCong.getNgayPhanCong(),
                phanCong.getNgayHoanThanh(),
                phanCong.getTrangThai()
            });
        }
        tblDanhSachPhanCong.setModel(model);

    }

    private void loadTableData2() {
        ChamCongCNDao chamCongCNDao = new ChamCongCNDao();
        List<ChamCongCN> chamCongList = chamCongCNDao.getAllChamCong();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Mã chấm công");
        model.addColumn("Mã công nhân");
        model.addColumn("Mã phân công");
        model.addColumn("Mã phân đoạn");
        model.addColumn("Số lượng cần làm");
        model.addColumn("Số lượng đã làm");
        model.addColumn("Ngày phân công");
        model.addColumn("Ca làm");
        model.addColumn("Hệ số lương ca");
        model.addColumn("Ngày chấm công");
        model.addColumn("Trạng thái");
        for (ChamCongCN chamCong : chamCongList) {
            model.addRow(new Object[]{
                chamCong.getMaChamCong(),
                chamCong.getPhanCong().getCongNhan().getMaCongNhan(),
                chamCong.getPhanCong().getMaPhanCong(),
                chamCong.getPhanCong().getPhanDoan().getMaPhanDoan(),
                chamCong.getPhanCong().getSoLuongCanLam(),
                chamCong.getSoLuongSanPham(),
                chamCong.getPhanCong().getNgayPhanCong(),
                chamCong.getCaLam(),
                chamCong.getHeSoLuongCa(),
                chamCong.getNgayChamCong(),
                chamCong.getTrangThai(),});
            tblDanhSachChamCong.setModel(model);
        }
    }

    private void xoaRong() {
        txtMaChamCong.setText("");
        txtSoLuongSanPham.setText("");
        txtHeSoCa.setText("");
        txtMaPhanCong.setText("");
        txtMaCongNhan.setText("");
    }

    private void xoaDuLieuTrongBang() {
        DefaultTableModel model = (DefaultTableModel) tblDanhSachChamCong.getModel();
        model.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTieuDe1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDanhSachPhanCong = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblMaSanPham = new javax.swing.JLabel();
        txtMaChamCong = new javax.swing.JTextField();
        lblMaSanPham6 = new javax.swing.JLabel();
        txtSoLuongSanPham = new javax.swing.JTextField();
        lblMaSanPham7 = new javax.swing.JLabel();
        txtHeSoCa = new javax.swing.JTextField();
        lblMaSanPham9 = new javax.swing.JLabel();
        txtMaCongNhan = new javax.swing.JTextField();
        lblMaSanPham10 = new javax.swing.JLabel();
        txtNgayChamCong = new javax.swing.JTextField();
        lblMaSanPham11 = new javax.swing.JLabel();
        lblMaSanPham1 = new javax.swing.JLabel();
        txtMaPhanCong = new javax.swing.JTextField();
        jComboBoxTrangThai = new javax.swing.JComboBox<>();
        lblMaSanPham8 = new javax.swing.JLabel();
        jComboBoxCaLam = new javax.swing.JComboBox<>();
        pnlNutChucNang = new javax.swing.JPanel();
        btnChamCong = new javax.swing.JButton();
        btnXoaChamCong = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnXuatExcel = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnHienThi = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblDanhSachChamCong = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setPreferredSize(new java.awt.Dimension(1120, 824));

        lblTieuDe1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTieuDe1.setForeground(new java.awt.Color(51, 0, 255));
        lblTieuDe1.setText("CHẤM CÔNG CÔNG NHÂN");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách phân công", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        tblDanhSachPhanCong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDanhSachPhanCong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachPhanCongMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblDanhSachPhanCong);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        lblMaSanPham.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMaSanPham.setText("Mã chấm công:");

        lblMaSanPham6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMaSanPham6.setText("Số lượng đã làm:");

        lblMaSanPham7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMaSanPham7.setText("Hệ số ca:");

        lblMaSanPham9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMaSanPham9.setText("Mã công nhân:");

        lblMaSanPham10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMaSanPham10.setText("Ngày chấm công:");

        lblMaSanPham11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMaSanPham11.setText("Trạng thái:");

        lblMaSanPham1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMaSanPham1.setText("Mã phân công:");

        jComboBoxTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Có mặt", "Vắng mặt", "Nghỉ phép" }));

        lblMaSanPham8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMaSanPham8.setText("Ca làm:");

        jComboBoxCaLam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ca Sáng", "Ca Tối" }));
        jComboBoxCaLam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCaLamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblMaSanPham6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSoLuongSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblMaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaChamCong, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblMaSanPham7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHeSoCa, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblMaSanPham8, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxCaLam, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lblMaSanPham9, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtMaCongNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblMaSanPham11, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblMaSanPham10, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNgayChamCong, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblMaSanPham1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaPhanCong, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaChamCong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaPhanCong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaSanPham1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaCongNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaSanPham9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNgayChamCong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaSanPham10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblMaSanPham11, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jComboBoxTrangThai)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSoLuongSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaSanPham6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblMaSanPham8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxCaLam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHeSoCa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaSanPham7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27))
        );

        btnChamCong.setBackground(new java.awt.Color(204, 255, 204));
        btnChamCong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnChamCong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/them.png"))); // NOI18N
        btnChamCong.setText("Chấm công");
        btnChamCong.setMargin(new java.awt.Insets(2, 2, 3, 2));
        btnChamCong.setMaximumSize(new java.awt.Dimension(115, 37));
        btnChamCong.setMinimumSize(new java.awt.Dimension(115, 37));
        btnChamCong.setPreferredSize(new java.awt.Dimension(125, 37));
        btnChamCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChamCongActionPerformed(evt);
            }
        });

        btnXoaChamCong.setBackground(new java.awt.Color(204, 255, 204));
        btnXoaChamCong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXoaChamCong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icon-ThoiViec.png"))); // NOI18N
        btnXoaChamCong.setText("Xóa");
        btnXoaChamCong.setMargin(new java.awt.Insets(2, 2, 3, 2));
        btnXoaChamCong.setPreferredSize(new java.awt.Dimension(125, 23));
        btnXoaChamCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaChamCongActionPerformed(evt);
            }
        });

        btnLamMoi.setBackground(new java.awt.Color(204, 255, 204));
        btnLamMoi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icon-LamMoi.png"))); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.setMargin(new java.awt.Insets(2, 2, 3, 2));
        btnLamMoi.setPreferredSize(new java.awt.Dimension(125, 22));
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnXuatExcel.setBackground(new java.awt.Color(204, 255, 204));
        btnXuatExcel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXuatExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icon-XuatExcel.png"))); // NOI18N
        btnXuatExcel.setText("Xuất Excel");
        btnXuatExcel.setMargin(new java.awt.Insets(2, 0, 3, 0));
        btnXuatExcel.setPreferredSize(new java.awt.Dimension(125, 22));

        btnThoat.setBackground(new java.awt.Color(204, 255, 204));
        btnThoat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icon-thoatPanel.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.setMargin(new java.awt.Insets(2, 2, 3, 2));
        btnThoat.setPreferredSize(new java.awt.Dimension(125, 23));
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnHienThi.setBackground(new java.awt.Color(204, 255, 204));
        btnHienThi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnHienThi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icon-ThoiViec.png"))); // NOI18N
        btnHienThi.setText("Xem");
        btnHienThi.setMargin(new java.awt.Insets(2, 2, 3, 2));
        btnHienThi.setPreferredSize(new java.awt.Dimension(125, 23));
        btnHienThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienThiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNutChucNangLayout = new javax.swing.GroupLayout(pnlNutChucNang);
        pnlNutChucNang.setLayout(pnlNutChucNangLayout);
        pnlNutChucNangLayout.setHorizontalGroup(
            pnlNutChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNutChucNangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHienThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnChamCong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnXoaChamCong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnXuatExcel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlNutChucNangLayout.setVerticalGroup(
            pnlNutChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNutChucNangLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(pnlNutChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChamCong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaChamCong, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXuatExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHienThi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách chấm công", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        tblDanhSachChamCong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDanhSachChamCong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachChamCongMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblDanhSachChamCong);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlNutChucNang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(630, 630, 630)
                .addComponent(lblTieuDe1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblTieuDe1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(pnlNutChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnChamCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChamCongActionPerformed
        // TODO add your handling code here:
        String maChamCong = txtMaChamCong.getText();
        String maPhanCong = txtMaPhanCong.getText();
        int soLuongSanPham = Integer.parseInt(txtSoLuongSanPham.getText());
        float heSoLuongCa = Float.parseFloat(txtHeSoCa.getText());
        String caLam = (String) jComboBoxCaLam.getSelectedItem();
        String trangThai = (String) jComboBoxTrangThai.getSelectedItem();
        String ngayChamCong = txtNgayChamCong.getText();
        PhanCong phanCong = new PhanCong();
        phanCong.setMaPhanCong(maPhanCong);
        ChamCongCN chamCong = new ChamCongCN(maChamCong, phanCong, soLuongSanPham, heSoLuongCa, caLam, trangThai);
        ChamCongCNDao chamCongCNDao = new ChamCongCNDao();
        boolean result = chamCongCNDao.themChamCongCongNhan(chamCong);
        if (result) {
            JOptionPane.showMessageDialog(this, "Thêm chấm công thành công");
            loadTableData2();
        } else {
            JOptionPane.showMessageDialog(this, "Thêm chấm công không thành công");
        }
    }//GEN-LAST:event_btnChamCongActionPerformed

    private void tblDanhSachPhanCongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachPhanCongMouseClicked
        // TODO add your handling code here:
        int row = tblDanhSachPhanCong.getSelectedRow();
        if (row != -1) {
            txtMaPhanCong.setText(tblDanhSachPhanCong.getValueAt(row, 0).toString());
            txtMaCongNhan.setText(tblDanhSachPhanCong.getValueAt(row, 2).toString());
        }
    }//GEN-LAST:event_tblDanhSachPhanCongMouseClicked

    private void tblDanhSachChamCongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachChamCongMouseClicked
        int row = tblDanhSachChamCong.getSelectedRow();
        if (row != -1) {
            txtMaChamCong.setText(tblDanhSachChamCong.getValueAt(row, 0).toString());
            txtMaCongNhan.setText(tblDanhSachChamCong.getValueAt(row, 1).toString());
            txtMaPhanCong.setText(tblDanhSachChamCong.getValueAt(row, 2).toString());
            txtSoLuongSanPham.setText(tblDanhSachChamCong.getValueAt(row, 5).toString());
            txtHeSoCa.setText(tblDanhSachChamCong.getValueAt(row, 8).toString());
            jComboBoxCaLam.setSelectedItem(tblDanhSachChamCong.getValueAt(row, 7));
            jComboBoxTrangThai.setSelectedItem(tblDanhSachChamCong.getValueAt(row, 10));
        }
    }//GEN-LAST:event_tblDanhSachChamCongMouseClicked

    private void btnXoaChamCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaChamCongActionPerformed
        // TODO add your handling code here:
        int row = tblDanhSachChamCong.getSelectedRow();
        if (row != -1) {
            String maChamCong = tblDanhSachChamCong.getValueAt(row, 0).toString();

            if (chamCongCNDao.xoaChamCong(maChamCong)) {
                JOptionPane.showMessageDialog(this, "Xóa phân đoạn thành công");
                loadTableData2();
            } else {
                JOptionPane.showMessageDialog(this, "Xóa phân đoạn không thành công");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn phân đoạn để xóa");
        }

    }//GEN-LAST:event_btnXoaChamCongActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        SwingUtilities.getWindowAncestor(this).dispose();
        this.setVisible(false);
        new TrangChu_GUI().setVisible(true);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        xoaRong();
        xoaDuLieuTrongBang();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnHienThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienThiActionPerformed
        // TODO add your handling code here:
        loadTableData2();
    }//GEN-LAST:event_btnHienThiActionPerformed

    private void jComboBoxCaLamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCaLamActionPerformed
        // TODO add your handling code here:
        String selectedCa = jComboBoxCaLam.getSelectedItem().toString();
        if (selectedCa.equals("Ca Sáng")) {
            txtHeSoCa.setText("1.2");
        } else if (selectedCa.equals("Ca Tối")) {
            txtHeSoCa.setText("1.5");
        }
    }//GEN-LAST:event_jComboBoxCaLamActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChamCong;
    private javax.swing.JButton btnHienThi;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoaChamCong;
    private javax.swing.JButton btnXuatExcel;
    private javax.swing.JComboBox<String> jComboBoxCaLam;
    private javax.swing.JComboBox<String> jComboBoxTrangThai;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblMaSanPham;
    private javax.swing.JLabel lblMaSanPham1;
    private javax.swing.JLabel lblMaSanPham10;
    private javax.swing.JLabel lblMaSanPham11;
    private javax.swing.JLabel lblMaSanPham6;
    private javax.swing.JLabel lblMaSanPham7;
    private javax.swing.JLabel lblMaSanPham8;
    private javax.swing.JLabel lblMaSanPham9;
    private javax.swing.JLabel lblTieuDe1;
    private javax.swing.JPanel pnlNutChucNang;
    private javax.swing.JTable tblDanhSachChamCong;
    private javax.swing.JTable tblDanhSachPhanCong;
    private javax.swing.JTextField txtHeSoCa;
    private javax.swing.JTextField txtMaChamCong;
    private javax.swing.JTextField txtMaCongNhan;
    private javax.swing.JTextField txtMaPhanCong;
    private javax.swing.JTextField txtNgayChamCong;
    private javax.swing.JTextField txtSoLuongSanPham;
    // End of variables declaration//GEN-END:variables
}
