/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import dao.CongNhanDao;
import entity.CongNhan;
import helper.XuatFileExcel;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author huylauri
 */
public class FrmTimKiemCongNhan extends javax.swing.JPanel {

    private final CongNhanDao CongNhanDao;

    public FrmTimKiemCongNhan() {
        initComponents();
        CongNhanDao = new CongNhanDao();
        checkOut();
    }

    private void xoaDuLieuTrongBang() {
        DefaultTableModel model = (DefaultTableModel) tblDanhSachCongNhan.getModel();
        model.setRowCount(0);
    }

    private void xoaRong() {
        txtMaCongNhan.setText("");
        txtTenCongNhan.setText("");
        txtDiaChi.setText("");
        txtSoDienThoai.setText("");
        txtEmail.setText("");
    }
    
    private void checkOut() {
        txtTenCongNhan.setEnabled(false);
        txtMaCongNhan.setEnabled(false);
        txtEmail.setEnabled(false);
        txtDiaChi.setEnabled(false);
        txtSoDienThoai.setEnabled(false);
        txtCMND.setEnabled(false);
    }

    private void hienThiCongNhan(List<CongNhan> congNhans) {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Mã công nhân");
        model.addColumn("Tên công nhân");
        model.addColumn("Ngày sinh");
        model.addColumn("Giới tính");
        model.addColumn("Địa chỉ");
        model.addColumn("Số điện thoại");
        model.addColumn("Email");
        model.addColumn("CMND");
        model.addColumn("Ngày bắt đầu làm");
        model.addColumn("Trợ cấp");
        model.addColumn("Tay nghề");

        for (CongNhan congNhan : congNhans) {
            Object[] row = new Object[]{
                congNhan.getMaCongNhan(),
                congNhan.getTenCongNhan(),
                congNhan.getNgaySinh(),
                congNhan.isGioiTinh() ? "Nam" : "Nữ",
                congNhan.getDiaChi(),
                congNhan.getSoDienThoai(),
                congNhan.getEmail(),
                congNhan.getCmnd(),
                congNhan.getNgayBatDau(),
                congNhan.getTroCap(),
                congNhan.getTayNghe()
            };
            model.addRow(row);
        }

        tblDanhSachCongNhan.setModel(model);
    }

    private void timKiemCongNhan() {
        String maCongNhan = txtMaCongNhan.getText().trim();
        String tenCongNhan = txtTenCongNhan.getText().trim();
        String diaChi = txtDiaChi.getText().trim();
        String soDienThoai = txtSoDienThoai.getText().trim();
        String email = txtEmail.getText().trim();
        String cmnd = txtCMND.getText().trim();

        // Kiểm tra nếu tất cả các trường đều rỗng thì yêu cầu người dùng nhập ít nhất 1 thông tin tìm kiếm
        if (maCongNhan.isEmpty() && tenCongNhan.isEmpty() && diaChi.isEmpty() && soDienThoai.isEmpty() && email.isEmpty() && cmnd.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vùi lòng nhập ít nhất một thông tin tìm kiếm", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        List<CongNhan> congNhans = CongNhanDao.timKiemCongNhan(maCongNhan, tenCongNhan, diaChi, soDienThoai, email, cmnd);
        if (congNhans.isEmpty()) {
            xoaDuLieuTrongBang();
            JOptionPane.showMessageDialog(this, "Không tìm thấy công nhân nào phù hợp", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            hienThiCongNhan(congNhans);
            JOptionPane.showMessageDialog(this, "Tìm kiếm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTieuDe1 = new javax.swing.JLabel();
        pnlThongTinTimKiem = new javax.swing.JPanel();
        txtMaCongNhan = new javax.swing.JTextField();
        txtTenCongNhan = new javax.swing.JTextField();
        txtSoDienThoai = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtCMND = new javax.swing.JTextField();
        radMaCongNhan = new javax.swing.JRadioButton();
        radDiaChi = new javax.swing.JRadioButton();
        radSoDienThoai = new javax.swing.JRadioButton();
        radEmail = new javax.swing.JRadioButton();
        radTenCongNhan = new javax.swing.JRadioButton();
        radCMND = new javax.swing.JRadioButton();
        pnlNutChucNang = new javax.swing.JPanel();
        btnTimKiem = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnXuatExcel = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSachCongNhan = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setPreferredSize(new java.awt.Dimension(1120, 824));

        lblTieuDe1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTieuDe1.setForeground(new java.awt.Color(51, 0, 255));
        lblTieuDe1.setText("TÌM KIẾM CÔNG NHÂN");

        pnlThongTinTimKiem.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm công nhân", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        radMaCongNhan.setText("Mã công nhân:");
        radMaCongNhan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radMaCongNhanItemStateChanged(evt);
            }
        });
        radMaCongNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radMaCongNhanActionPerformed(evt);
            }
        });

        radDiaChi.setText("Địa chỉ:");
        radDiaChi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radDiaChiItemStateChanged(evt);
            }
        });
        radDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radDiaChiActionPerformed(evt);
            }
        });

        radSoDienThoai.setText("Số điện thoại:");
        radSoDienThoai.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radSoDienThoaiItemStateChanged(evt);
            }
        });
        radSoDienThoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radSoDienThoaiActionPerformed(evt);
            }
        });

        radEmail.setText("Email:");
        radEmail.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radEmailItemStateChanged(evt);
            }
        });
        radEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radEmailActionPerformed(evt);
            }
        });

        radTenCongNhan.setText("Tên công nhân:");
        radTenCongNhan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radTenCongNhanItemStateChanged(evt);
            }
        });
        radTenCongNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radTenCongNhanActionPerformed(evt);
            }
        });

        radCMND.setText("CMND:");
        radCMND.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radCMNDItemStateChanged(evt);
            }
        });
        radCMND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radCMNDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlThongTinTimKiemLayout = new javax.swing.GroupLayout(pnlThongTinTimKiem);
        pnlThongTinTimKiem.setLayout(pnlThongTinTimKiemLayout);
        pnlThongTinTimKiemLayout.setHorizontalGroup(
            pnlThongTinTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinTimKiemLayout.createSequentialGroup()
                .addContainerGap(213, Short.MAX_VALUE)
                .addGroup(pnlThongTinTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlThongTinTimKiemLayout.createSequentialGroup()
                        .addComponent(radMaCongNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaCongNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlThongTinTimKiemLayout.createSequentialGroup()
                        .addComponent(radTenCongNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenCongNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlThongTinTimKiemLayout.createSequentialGroup()
                        .addComponent(radDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(92, 92, 92)
                .addGroup(pnlThongTinTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlThongTinTimKiemLayout.createSequentialGroup()
                        .addComponent(radSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSoDienThoai))
                    .addGroup(pnlThongTinTimKiemLayout.createSequentialGroup()
                        .addComponent(radCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlThongTinTimKiemLayout.createSequentialGroup()
                        .addComponent(radEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(203, 203, 203))
        );
        pnlThongTinTimKiemLayout.setVerticalGroup(
            pnlThongTinTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinTimKiemLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnlThongTinTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlThongTinTimKiemLayout.createSequentialGroup()
                        .addGroup(pnlThongTinTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaCongNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radMaCongNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlThongTinTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenCongNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radTenCongNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlThongTinTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlThongTinTimKiemLayout.createSequentialGroup()
                        .addGroup(pnlThongTinTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlThongTinTimKiemLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(pnlThongTinTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(radEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(13, 13, 13)
                        .addGroup(pnlThongTinTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        btnTimKiem.setBackground(new java.awt.Color(102, 255, 102));
        btnTimKiem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icon-tìmkiemNV.png"))); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.setMargin(new java.awt.Insets(2, 2, 3, 2));
        btnTimKiem.setMaximumSize(new java.awt.Dimension(115, 37));
        btnTimKiem.setMinimumSize(new java.awt.Dimension(115, 37));
        btnTimKiem.setPreferredSize(new java.awt.Dimension(125, 37));
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnLamMoi.setBackground(new java.awt.Color(255, 255, 51));
        btnLamMoi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icon-LamMoi.png"))); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.setMargin(new java.awt.Insets(2, 2, 3, 2));
        btnLamMoi.setPreferredSize(new java.awt.Dimension(125, 22));
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnXuatExcel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXuatExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icon-XuatExcel.png"))); // NOI18N
        btnXuatExcel.setText("Xuất Excel");
        btnXuatExcel.setMargin(new java.awt.Insets(2, 0, 3, 0));
        btnXuatExcel.setPreferredSize(new java.awt.Dimension(125, 22));
        btnXuatExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatExcelActionPerformed(evt);
            }
        });

        btnThoat.setBackground(new java.awt.Color(255, 102, 102));
        btnThoat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icon-thoat.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.setMargin(new java.awt.Insets(2, 2, 3, 2));
        btnThoat.setPreferredSize(new java.awt.Dimension(125, 23));
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNutChucNangLayout = new javax.swing.GroupLayout(pnlNutChucNang);
        pnlNutChucNang.setLayout(pnlNutChucNangLayout);
        pnlNutChucNangLayout.setHorizontalGroup(
            pnlNutChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNutChucNangLayout.createSequentialGroup()
                .addGap(372, 372, 372)
                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnXuatExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(391, Short.MAX_VALUE))
        );
        pnlNutChucNangLayout.setVerticalGroup(
            pnlNutChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNutChucNangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlNutChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlNutChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnXuatExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách công nhân tìm thấy", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        tblDanhSachCongNhan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDanhSachCongNhan);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTieuDe1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(pnlNutChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlThongTinTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTieuDe1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlThongTinTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlNutChucNang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        xoaRong();
        xoaDuLieuTrongBang();
        JOptionPane.showMessageDialog(this, "Làm mới thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        SwingUtilities.getWindowAncestor(this).dispose();
        this.setVisible(false);
        new TrangChu_GUI().setVisible(true);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        timKiemCongNhan();
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void radMaCongNhanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radMaCongNhanItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_radMaCongNhanItemStateChanged

    private void radMaCongNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radMaCongNhanActionPerformed
        // TODO add your handling code here:
        if (radMaCongNhan.isSelected()) {
            txtMaCongNhan.setEnabled(true);
        } else {
            txtMaCongNhan.setEnabled(false);
        }
    }//GEN-LAST:event_radMaCongNhanActionPerformed

    private void radDiaChiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radDiaChiItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_radDiaChiItemStateChanged

    private void radDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radDiaChiActionPerformed
        // TODO add your handling code here:
        if (radDiaChi.isSelected()) {
            txtDiaChi.setEnabled(true);
        } else {
            txtDiaChi.setEnabled(false);
        }
    }//GEN-LAST:event_radDiaChiActionPerformed

    private void radSoDienThoaiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radSoDienThoaiItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_radSoDienThoaiItemStateChanged

    private void radSoDienThoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radSoDienThoaiActionPerformed
        // TODO add your handling code here:
        if (radSoDienThoai.isSelected()) {
            txtSoDienThoai.setEnabled(true);
        } else {
            txtSoDienThoai.setEnabled(false);
        }
    }//GEN-LAST:event_radSoDienThoaiActionPerformed

    private void radEmailItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radEmailItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_radEmailItemStateChanged

    private void radEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radEmailActionPerformed
        // TODO add your handling code here:
        if (radEmail.isSelected()) {
            txtEmail.setEnabled(true);
        } else {
            txtEmail.setEnabled(false);
        }
    }//GEN-LAST:event_radEmailActionPerformed

    private void radTenCongNhanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radTenCongNhanItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_radTenCongNhanItemStateChanged

    private void radTenCongNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radTenCongNhanActionPerformed
        // TODO add your handling code here:
        if (radTenCongNhan.isSelected()) {
            txtTenCongNhan.setEnabled(true);
        } else {
            txtTenCongNhan.setEnabled(false);
        }
    }//GEN-LAST:event_radTenCongNhanActionPerformed

    private void radCMNDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radCMNDItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_radCMNDItemStateChanged

    private void radCMNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radCMNDActionPerformed
        // TODO add your handling code here:
        if (radCMND.isSelected()) {
            txtCMND.setEnabled(true);
        } else {
            txtCMND.setEnabled(false);
        }
    }//GEN-LAST:event_radCMNDActionPerformed

    private void btnXuatExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatExcelActionPerformed
        // TODO add your handling code here:
        XuatFileExcel.xuatFileExcel(tblDanhSachCongNhan);
    }//GEN-LAST:event_btnXuatExcelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXuatExcel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTieuDe1;
    private javax.swing.JPanel pnlNutChucNang;
    private javax.swing.JPanel pnlThongTinTimKiem;
    private javax.swing.JRadioButton radCMND;
    private javax.swing.JRadioButton radDiaChi;
    private javax.swing.JRadioButton radEmail;
    private javax.swing.JRadioButton radMaCongNhan;
    private javax.swing.JRadioButton radSoDienThoai;
    private javax.swing.JRadioButton radTenCongNhan;
    private javax.swing.JTable tblDanhSachCongNhan;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMaCongNhan;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTenCongNhan;
    // End of variables declaration//GEN-END:variables
}
