/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import dao.BangLuongCNDao;

import dao.ChamCongCNDao;

import dao.CongNhanDao;

import entity.BangLuongCN;

import entity.ChamCongCN;

import entity.CongNhan;
import entity.CongNhanDaChamCong;
import entity.PhanCong;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author duy19
 */
public class FrmTinhLuongCongNhan extends javax.swing.JPanel {

    private DefaultTableModel model, model1;
    private CongNhanDao cn_dao = new CongNhanDao();
    private ChamCongCNDao chamCongCN_dao = new ChamCongCNDao();
    private BangLuongCNDao bangLuongCN_dao = new BangLuongCNDao();

    /**
     * Creates new form FrmTinhLuongCongNhan
     */
    public FrmTinhLuongCongNhan() {
        initComponents();
        initTable();
        loadDataToTable();
        initTableTinhLuong();
        loadDataToTableTinhLuong();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblDSCongNhanDaChamCong = new javax.swing.JTable();
        ThongTinPC = new javax.swing.JPanel();
        lblMaSanPham = new javax.swing.JLabel();
        txtMaCN = new javax.swing.JTextField();
        lblMaSanPham1 = new javax.swing.JLabel();
        lblMaSanPham3 = new javax.swing.JLabel();
        lblMaSanPham4 = new javax.swing.JLabel();
        txtTenCN = new javax.swing.JTextField();
        lblMaSanPham6 = new javax.swing.JLabel();
        jDateNgayLap = new com.toedter.calendar.JDateChooser();
        lblMaSanPham7 = new javax.swing.JLabel();
        jDateNgaySinh = new com.toedter.calendar.JDateChooser();
        txtThangLuong = new javax.swing.JTextField();
        lblMaSanPham9 = new javax.swing.JLabel();
        lblMaSanPham10 = new javax.swing.JLabel();
        txtNamLuong = new javax.swing.JTextField();
        txtTroCap = new javax.swing.JTextField();
        lblMaSanPham12 = new javax.swing.JLabel();
        txtSLDaLam = new javax.swing.JTextField();
        lblMaSanPham14 = new javax.swing.JLabel();
        lblMaSanPham15 = new javax.swing.JLabel();
        txtHeSoCa = new javax.swing.JTextField();
        cmbGioiTinh = new javax.swing.JComboBox<>();
        txtCaLam = new javax.swing.JTextField();
        lblMaSanPham13 = new javax.swing.JLabel();
        txtGiaPhanDoan = new javax.swing.JTextField();
        lblMaSanPham11 = new javax.swing.JLabel();
        txtMaPhieuLuong = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblDSTinhLuong = new javax.swing.JTable();
        pnlNutChucNang = new javax.swing.JPanel();
        btnTinhLuong = new javax.swing.JButton();
        btnXoaRong = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnInBangLuong = new javax.swing.JButton();
        lblTieuDe = new javax.swing.JLabel();

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách công nhân đã chấm công", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        tblDSCongNhanDaChamCong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDSCongNhanDaChamCong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSCongNhanDaChamCongMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblDSCongNhanDaChamCong);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
        );

        lblMaSanPham.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMaSanPham.setText("Mã công nhân:");

        txtMaCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaCNActionPerformed(evt);
            }
        });

        lblMaSanPham1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMaSanPham1.setText("Tên công nhân");

        lblMaSanPham3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMaSanPham3.setText("Giới tính");

        lblMaSanPham4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMaSanPham4.setText("Ngày lập ");

        txtTenCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenCNActionPerformed(evt);
            }
        });

        lblMaSanPham6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMaSanPham6.setText("Trợ cấp");

        jDateNgayLap.setDateFormatString("dd/MM/yyyy");

        lblMaSanPham7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMaSanPham7.setText("Ngày sinh");

        jDateNgaySinh.setDateFormatString("dd/MM/yyyy");

        txtThangLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThangLuongActionPerformed(evt);
            }
        });

        lblMaSanPham9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMaSanPham9.setText("Tháng lương");

        lblMaSanPham10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMaSanPham10.setText("Năm lương");

        txtNamLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamLuongActionPerformed(evt);
            }
        });

        txtTroCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTroCapActionPerformed(evt);
            }
        });

        lblMaSanPham12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMaSanPham12.setText("Số lượng đã làm");

        txtSLDaLam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSLDaLamActionPerformed(evt);
            }
        });

        lblMaSanPham14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMaSanPham14.setText("Ca làm");

        lblMaSanPham15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMaSanPham15.setText("Hệ số ca");

        txtHeSoCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeSoCaActionPerformed(evt);
            }
        });

        cmbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        cmbGioiTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGioiTinhActionPerformed(evt);
            }
        });

        lblMaSanPham13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMaSanPham13.setText("Giá phân đoạn");

        txtGiaPhanDoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaPhanDoanActionPerformed(evt);
            }
        });

        lblMaSanPham11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMaSanPham11.setText("Mã phiếu lương");

        txtMaPhieuLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaPhieuLuongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ThongTinPCLayout = new javax.swing.GroupLayout(ThongTinPC);
        ThongTinPC.setLayout(ThongTinPCLayout);
        ThongTinPCLayout.setHorizontalGroup(
            ThongTinPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongTinPCLayout.createSequentialGroup()
                .addGroup(ThongTinPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ThongTinPCLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ThongTinPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ThongTinPCLayout.createSequentialGroup()
                                .addComponent(lblMaSanPham9, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtThangLuong))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThongTinPCLayout.createSequentialGroup()
                                .addComponent(lblMaSanPham11, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaPhieuLuong))
                            .addGroup(ThongTinPCLayout.createSequentialGroup()
                                .addComponent(lblMaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaCN))
                            .addGroup(ThongTinPCLayout.createSequentialGroup()
                                .addComponent(lblMaSanPham3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbGioiTinh, 0, 162, Short.MAX_VALUE))
                            .addGroup(ThongTinPCLayout.createSequentialGroup()
                                .addComponent(lblMaSanPham13, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGiaPhanDoan))
                            .addGroup(ThongTinPCLayout.createSequentialGroup()
                                .addComponent(lblMaSanPham12, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSLDaLam))))
                    .addGroup(ThongTinPCLayout.createSequentialGroup()
                        .addComponent(lblMaSanPham6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTroCap)))
                .addGap(29, 29, 29)
                .addGroup(ThongTinPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ThongTinPCLayout.createSequentialGroup()
                        .addGroup(ThongTinPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaSanPham1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaSanPham7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaSanPham10, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ThongTinPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(txtNamLuong)
                            .addComponent(txtTenCN)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ThongTinPCLayout.createSequentialGroup()
                        .addGroup(ThongTinPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaSanPham4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaSanPham14, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaSanPham15, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(ThongTinPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHeSoCa)
                            .addComponent(jDateNgayLap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCaLam))))
                .addGap(38, 38, 38))
        );
        ThongTinPCLayout.setVerticalGroup(
            ThongTinPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongTinPCLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(ThongTinPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaSanPham1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(ThongTinPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ThongTinPCLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(ThongTinPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaSanPham3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ThongTinPCLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ThongTinPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaSanPham7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12)
                .addGroup(ThongTinPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaPhieuLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaSanPham11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaSanPham10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ThongTinPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ThongTinPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtThangLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblMaSanPham9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblMaSanPham4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(ThongTinPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ThongTinPCLayout.createSequentialGroup()
                        .addGroup(ThongTinPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaSanPham6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTroCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ThongTinPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaSanPham12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSLDaLam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ThongTinPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaSanPham13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGiaPhanDoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ThongTinPCLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(ThongTinPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaSanPham14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCaLam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ThongTinPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaSanPham15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHeSoCa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách tính lương", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        tblDSTinhLuong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDSTinhLuong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSTinhLuongMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblDSTinhLuong);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 1206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnTinhLuong.setBackground(new java.awt.Color(204, 255, 204));
        btnTinhLuong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTinhLuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/them.png"))); // NOI18N
        btnTinhLuong.setText("Tính Lương");
        btnTinhLuong.setMargin(new java.awt.Insets(2, 2, 3, 2));
        btnTinhLuong.setPreferredSize(new java.awt.Dimension(125, 22));
        btnTinhLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhLuongActionPerformed(evt);
            }
        });

        btnXoaRong.setBackground(new java.awt.Color(0, 206, 245));
        btnXoaRong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXoaRong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icon-bochon.png"))); // NOI18N
        btnXoaRong.setText("Xóa rỗng");
        btnXoaRong.setMargin(new java.awt.Insets(2, 0, 3, 0));
        btnXoaRong.setPreferredSize(new java.awt.Dimension(125, 22));
        btnXoaRong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaRongActionPerformed(evt);
            }
        });

        btnThoat.setBackground(new java.awt.Color(252, 33, 30));
        btnThoat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icon-thoat.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.setMargin(new java.awt.Insets(2, 2, 3, 2));
        btnThoat.setPreferredSize(new java.awt.Dimension(125, 23));
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnInBangLuong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnInBangLuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icon-in.png"))); // NOI18N
        btnInBangLuong.setText("In Bảng lương");
        btnInBangLuong.setMargin(new java.awt.Insets(2, 0, 3, 0));
        btnInBangLuong.setPreferredSize(new java.awt.Dimension(125, 23));
        btnInBangLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInBangLuongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNutChucNangLayout = new javax.swing.GroupLayout(pnlNutChucNang);
        pnlNutChucNang.setLayout(pnlNutChucNangLayout);
        pnlNutChucNangLayout.setHorizontalGroup(
            pnlNutChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNutChucNangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTinhLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnXoaRong, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnInBangLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlNutChucNangLayout.setVerticalGroup(
            pnlNutChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNutChucNangLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnlNutChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTinhLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaRong, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInBangLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTieuDe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTieuDe.setForeground(new java.awt.Color(51, 0, 255));
        lblTieuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTieuDe.setText("TÍNH LƯƠNG CÔNG NHÂN");
        lblTieuDe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlNutChucNang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(ThongTinPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 68, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTieuDe)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ThongTinPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlNutChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(230, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void initTable() {
        model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{"Mã chấm công", "Mã công nhân", "Tên công nhân", "Giới tính", "Ngày sinh", "Số điện thoại",
            "Tay nghề", "Trợ cấp"});
        tblDSCongNhanDaChamCong.setModel(model);
    }

    private void initTableTinhLuong() {
        model1 = new DefaultTableModel();
        model1.setColumnIdentifiers(new String[]{"Mã phiếu lương", "Mã công nhân", "Năm lương", "Tháng lương", "Số lượng đã làm", "Tổng Lương",
            "Ngày lập"});
        tblDSTinhLuong.setModel(model1);
    }

    public void loadDataToTable() {
        try {
            List<ChamCongCN> list = chamCongCN_dao.getAllChamCong();
            model.setRowCount(0);
            for (ChamCongCN chamCong : list) {
                {
                    model.addRow(new Object[]{
                        chamCong.getMaChamCong(), chamCong.getPhanCong().getCongNhan().getMaCongNhan(),
                        chamCong.getPhanCong().getCongNhan().getTenCongNhan(),
                        chamCong.getPhanCong().getCongNhan().isGioiTinh() ? "Nam" : "Nữ",
                        chamCong.getPhanCong().getCongNhan().getNgaySinh(),
                        chamCong.getPhanCong().getCongNhan().getSoDienThoai(),
                        chamCong.getPhanCong().getCongNhan().getTayNghe(),
                        chamCong.getPhanCong().getCongNhan().getTroCap()
                    });
                }
            }

            model.fireTableDataChanged();
        } catch (Exception e) {
        }
    }

    public void loadDataToTableTinhLuong() {
        try {
            List<BangLuongCN> list = bangLuongCN_dao.getDSLuongCN();
            model1.setRowCount(0);
            for (BangLuongCN bang : list) {
                {
                    model1.addRow(new Object[]{
                        bang.getMaPhieuLuong(),
                        bang.getChamCongCN().getPhanCong().getCongNhan().getMaCongNhan(),
                        bang.getNamLuong(),
                        bang.getThangLuong(),
                        bang.getChamCongCN().getSoLuongSanPham(),
                        bang.getTongLuong(),
                        bang.getNgaylap()
                    });
                }
            }

            model1.fireTableDataChanged();
        } catch (Exception e) {
        }
    }
    private void tblDSCongNhanDaChamCongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSCongNhanDaChamCongMouseClicked
        // TODO add your handling code here:
        try {
            int row = tblDSCongNhanDaChamCong.getSelectedRow();
            //JCalendar calendar = Calendar.getInstance();
            if (row >= 0) {
                String id = (String) tblDSCongNhanDaChamCong.getValueAt(row, 1);
                String maChamCong = (String) tblDSCongNhanDaChamCong.getValueAt(row, 0);
                CongNhanDao dao = new CongNhanDao();
                CongNhan cn = dao.getCNByID(id);
                ChamCongCNDao chamCong_dao = new ChamCongCNDao();
                ChamCongCN chamCongCN = chamCong_dao.getChamCongByID(maChamCong);
                if (cn != null) {
                    txtMaCN.setText(cn.getMaCongNhan());
                    txtTenCN.setText(cn.getTenCongNhan());
                    txtTroCap.setText(cn.getTroCap().toString());
                    cmbGioiTinh.setSelectedItem(cn.isGioiTinh() ? "Nam" : "Nữ");
                    jDateNgaySinh.setDate(cn.getNgaySinh());

                }
                if (chamCongCN != null) {
                    txtSLDaLam.setText(chamCongCN.getSoLuongSanPham() + "");
                    txtCaLam.setText(chamCongCN.getCaLam());
                    if (txtCaLam.getText().equals("Ca Tối")) {
                        txtHeSoCa.setText(1.05 + "");
                    }

                }
                Calendar calendar = Calendar.getInstance();
                jDateNgayLap.setDate(calendar.getTime());
                int month = calendar.get(Calendar.MONTH) + 1;
                int year = calendar.get(Calendar.YEAR);
                txtNamLuong.setText(year + "");
                txtThangLuong.setText(month + "");
                txtGiaPhanDoan.setText(chamCongCN.getPhanCong().getCongDoan().getGiaPhanDoan() + "");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_tblDSCongNhanDaChamCongMouseClicked

    private void txtTenCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenCNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenCNActionPerformed

    private void txtThangLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThangLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThangLuongActionPerformed

    private void txtNamLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamLuongActionPerformed

    private void tblDSTinhLuongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSTinhLuongMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDSTinhLuongMouseClicked

    private void btnTinhLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhLuongActionPerformed
        // TODO add your handling code here:
        int row = tblDSCongNhanDaChamCong.getSelectedRow();
        try {
            int soLuongDaLam = Integer.parseInt(txtSLDaLam.getText());
            double giaPhanDoan = Double.parseDouble(txtGiaPhanDoan.getText());
            double heSo = Double.parseDouble(txtHeSoCa.getText());
            double troCap = Double.parseDouble(txtTroCap.getText());

            double tongLuong = soLuongDaLam * giaPhanDoan * heSo + troCap;
            CongNhan cn = cn_dao.getCNByID(txtMaCN.getText());
            Calendar calendar = Calendar.getInstance();
            ChamCongCN chamCongCN;
            chamCongCN = chamCongCN_dao.timChamCongTheoMaCN(cn.getMaCongNhan());
            BangLuongCN bangLuong;
            bangLuong = new BangLuongCN(txtMaPhieuLuong.getText(), Integer.parseInt(txtNamLuong.getText()), Integer.parseInt(txtThangLuong.getText()), chamCongCN, tongLuong);
            bangLuongCN_dao.themLuongCN(bangLuong);
        } catch (Exception ex) {
            Logger.getLogger(FrmTinhLuongCongNhan.class.getName()).log(Level.SEVERE, null, ex);
        }
        loadDataToTableTinhLuong();
        model.removeRow(row);
    }//GEN-LAST:event_btnTinhLuongActionPerformed

    private void btnXoaRongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaRongActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_btnXoaRongActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        SwingUtilities.getWindowAncestor(this).dispose();
        this.setVisible(false);
        new TrangChu_GUI().setVisible(true);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void txtTroCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTroCapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTroCapActionPerformed

    private void txtSLDaLamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSLDaLamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSLDaLamActionPerformed

    private void txtHeSoCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeSoCaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeSoCaActionPerformed

    private void txtMaCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaCNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaCNActionPerformed

    private void txtGiaPhanDoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaPhanDoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaPhanDoanActionPerformed

    private void txtMaPhieuLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaPhieuLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaPhieuLuongActionPerformed

    private void cmbGioiTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGioiTinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGioiTinhActionPerformed

    private void btnInBangLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInBangLuongActionPerformed
        try {
            int row = tblDSTinhLuong.getSelectedRow();
            String maBangLuong = model1.getValueAt(row, 0).toString();
            String maCN = model1.getValueAt(row, 1).toString();
            CongNhan cn = cn_dao.timCNTheoMa(maCN);
//            double luongCoBan = cn.getLuongCoBan();
            double phuCap = cn.getTroCap();

            int thangLuong = Integer.parseInt(model1.getValueAt(row, 3).toString());

            int namLuong = Integer.parseInt(model1.getValueAt(row, 2).toString());

//            double tongLuong = soLuongDaLam * giaPhanDoan * heSo + troCap;
            

            int soLuongDaLam = 0;
            Double giaPhanDoan = 0.0;
            Double heSo = 0.0;
            Double troCap = 0.0;
            
            
//            double tongLuong = luongCBTinh + luongNghiPhep + luongNgoaiGio + phuCap;
//            DecimalFormat decimalFormat = new DecimalFormat("#,##0.00");
//            Hashtable map = new Hashtable();
//            JasperReport report = JasperCompileManager.compileReport("src/main/java/report/rptChiTietLuong.jrxml");
//            map.put("maNV", maNV);
//            map.put("ngayCongChuan", ngayCongChuan);
//            map.put("ngayLamViecThucTe", ngayLamViecThucTe);
//            map.put("ngayNghiPhep", ngayNghiPhep);
//            map.put("ngayNgoaiGio", ngayNgoaiGio);
//            map.put("luongCoBan", decimalFormat.format(luongCBTinh));
//            map.put("nghiPhepHuongLuong", decimalFormat.format(luongNghiPhep));
//            map.put("luongNgoaiGio", decimalFormat.format(luongNgoaiGio));
//            map.put("namLuong", namLuong);
//            map.put("thangLuong", thangLuong);
//            map.put("tongLuong", decimalFormat.format(tongLuong));
//            map.put("phuCap", decimalFormat.format(phuCap));
//
//            Connection con = ConnectDB.getInstance().getConnection();
//
//            JasperPrint p = JasperFillManager.fillReport(report, map, con);
//            JasperViewer.viewReport(p, false);
//            JasperExportManager.exportReportToPdfFile(p, "test.pdf");
//        } catch (JRException ex) {
//            Logger.getLogger(FrmTinhLuongNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(FrmTinhLuongNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnInBangLuongActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JPanel ThongTinPC;
    private javax.swing.JButton btnInBangLuong;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTinhLuong;
    private javax.swing.JButton btnXoaRong;
    private javax.swing.JComboBox<String> cmbGioiTinh;
    private com.toedter.calendar.JDateChooser jDateNgayLap;
    private com.toedter.calendar.JDateChooser jDateNgaySinh;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lblMaSanPham;
    private javax.swing.JLabel lblMaSanPham1;
    private javax.swing.JLabel lblMaSanPham10;
    private javax.swing.JLabel lblMaSanPham11;
    private javax.swing.JLabel lblMaSanPham12;
    private javax.swing.JLabel lblMaSanPham13;
    private javax.swing.JLabel lblMaSanPham14;
    private javax.swing.JLabel lblMaSanPham15;
    private javax.swing.JLabel lblMaSanPham3;
    private javax.swing.JLabel lblMaSanPham4;
    private javax.swing.JLabel lblMaSanPham6;
    private javax.swing.JLabel lblMaSanPham7;
    private javax.swing.JLabel lblMaSanPham9;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JPanel pnlNutChucNang;
    private javax.swing.JTable tblDSCongNhanDaChamCong;
    private javax.swing.JTable tblDSTinhLuong;
    private javax.swing.JTextField txtCaLam;
    private static javax.swing.JTextField txtGiaPhanDoan;
    private static javax.swing.JTextField txtHeSoCa;
    private javax.swing.JTextField txtMaCN;
    private static javax.swing.JTextField txtMaPhieuLuong;
    private javax.swing.JTextField txtNamLuong;
    private static javax.swing.JTextField txtSLDaLam;
    private javax.swing.JTextField txtTenCN;
    private static javax.swing.JTextField txtThangLuong;
    private static javax.swing.JTextField txtTroCap;
    // End of variables declaration//GEN-END:variables
}
