package gui;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author duy19
 */
public class TrangChu_GUI extends javax.swing.JFrame {

    private FrmQuanLySanPham qlsp;
    private FrmQuanLyPhanDoan qlcd;
    private FrmTimKiemSanPham tksp;
    private FrmTimKiemCN tkcn;
    private FrmChamCongCN cccn;
    private FrmThongKeCN tklcn;
    private FrmQuanLyCongNhan qlcn;
    private FrmTinhLuongCN tlcn;
    private FrmPhanCongCN pc;

    /**
     * Creates new form TrangChu_GUI1
     */
    public TrangChu_GUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabNoiDung = new javax.swing.JTabbedPane();
        lblTenChuongTrinh = new javax.swing.JLabel();
        mnuChinh = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnDanhMuc = new javax.swing.JMenu();
        mniDMNhanVien = new javax.swing.JMenuItem();
        mniCongNhan = new javax.swing.JMenuItem();
        mniSanPham = new javax.swing.JMenuItem();
        mniPhanDoan = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mniPhanCong = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        mniChamCongCongNhan = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        mniTinhLuongCongNhan = new javax.swing.JMenuItem();
        mniTimKiem = new javax.swing.JMenu();
        mniTKNhanVien = new javax.swing.JMenuItem();
        mniTimKiemCongNhan = new javax.swing.JMenuItem();
        mniTimKiemSanPham = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mniThongKeCN = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        mniDangXuat = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setSize(new java.awt.Dimension(1600, 9));

        lblTenChuongTrinh.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTenChuongTrinh.setForeground(new java.awt.Color(255, 51, 0));
        lblTenChuongTrinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTenChuongTrinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/trangchu.jpeg"))); // NOI18N
        lblTenChuongTrinh.setText("CHƯƠNG TRÌNH QUẢN LÝ LƯƠNG SẢN PHẨM");
        lblTenChuongTrinh.setToolTipText("");
        lblTenChuongTrinh.setFocusable(false);
        lblTenChuongTrinh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTenChuongTrinh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tabNoiDung.addTab("Trang chính", lblTenChuongTrinh);

        mnuChinh.setBackground(new java.awt.Color(0, 0, 0));
        mnuChinh.setToolTipText("");
        mnuChinh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jMenu1.setBackground(new java.awt.Color(0, 0, 0));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/HOME.png"))); // NOI18N
        jMenu1.setText("Trang Chủ");
        jMenu1.setFocusable(false);
        jMenu1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mnuChinh.add(jMenu1);

        mnDanhMuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icon-danhmuc.png"))); // NOI18N
        mnDanhMuc.setText("Danh Mục");
        mnDanhMuc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        mniDMNhanVien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mniDMNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icon-Nhanvien.png"))); // NOI18N
        mniDMNhanVien.setText("Nhân viên");
        mniDMNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mniDMNhanVien.setPreferredSize(new java.awt.Dimension(25, 25));
        mniDMNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDMNhanVienActionPerformed(evt);
            }
        });
        mnDanhMuc.add(mniDMNhanVien);

        mniCongNhan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mniCongNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icon-Nhanvien.png"))); // NOI18N
        mniCongNhan.setText("Công nhân");
        mniCongNhan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mniCongNhan.setPreferredSize(new java.awt.Dimension(25, 25));
        mniCongNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mniCongNhanMouseClicked(evt);
            }
        });
        mniCongNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCongNhanActionPerformed(evt);
            }
        });
        mnDanhMuc.add(mniCongNhan);

        mniSanPham.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mniSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icon-Nhanvien.png"))); // NOI18N
        mniSanPham.setText("Sản phẩm");
        mniSanPham.setPreferredSize(new java.awt.Dimension(25, 25));
        mniSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSanPhamActionPerformed(evt);
            }
        });
        mnDanhMuc.add(mniSanPham);

        mniPhanDoan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mniPhanDoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icon-Nhanvien.png"))); // NOI18N
        mniPhanDoan.setText("Phân đoạn");
        mniPhanDoan.setPreferredSize(new java.awt.Dimension(150, 25));
        mniPhanDoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPhanDoanActionPerformed(evt);
            }
        });
        mnDanhMuc.add(mniPhanDoan);

        mnuChinh.add(mnDanhMuc);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icon-danhmuc.png"))); // NOI18N
        jMenu3.setText("Xử lý");
        jMenu3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        mniPhanCong.setText("Phân công");
        mniPhanCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPhanCongActionPerformed(evt);
            }
        });
        jMenu3.add(mniPhanCong);

        jMenuItem6.setText("Chấm công nhân viên");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        mniChamCongCongNhan.setText("Chấm công công nhân");
        mniChamCongCongNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniChamCongCongNhanActionPerformed(evt);
            }
        });
        jMenu3.add(mniChamCongCongNhan);

        jMenuItem8.setText("Tính lương nhân viên");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        mniTinhLuongCongNhan.setText("Tính lương công nhân");
        mniTinhLuongCongNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTinhLuongCongNhanActionPerformed(evt);
            }
        });
        jMenu3.add(mniTinhLuongCongNhan);

        mnuChinh.add(jMenu3);

        mniTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icon-timkiem2.png"))); // NOI18N
        mniTimKiem.setText("Tìm Kiếm");
        mniTimKiem.setAutoscrolls(true);
        mniTimKiem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mniTimKiem.setFocusPainted(true);
        mniTimKiem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mniTimKiem.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        mniTimKiem.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        mniTKNhanVien.setText("Nhân viên");
        mniTKNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTKNhanVienActionPerformed(evt);
            }
        });
        mniTimKiem.add(mniTKNhanVien);

        mniTimKiemCongNhan.setText("Công nhân");
        mniTimKiemCongNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTimKiemCongNhanActionPerformed(evt);
            }
        });
        mniTimKiem.add(mniTimKiemCongNhan);

        mniTimKiemSanPham.setText("Sản phẩm");
        mniTimKiemSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTimKiemSanPhamActionPerformed(evt);
            }
        });
        mniTimKiem.add(mniTimKiemSanPham);

        mnuChinh.add(mniTimKiem);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icon-danhmuc.png"))); // NOI18N
        jMenu5.setText("Thống Kê");
        jMenu5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        mniThongKeCN.setText("Công nhân");
        mniThongKeCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniThongKeCNActionPerformed(evt);
            }
        });
        jMenu5.add(mniThongKeCN);

        jMenuItem13.setText("Nhân viên");
        jMenu5.add(jMenuItem13);

        mnuChinh.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icon-danhmuc.png"))); // NOI18N
        jMenu6.setText("Tài Khoản");
        jMenu6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jMenuItem15.setText("Đăng ký tài khoản");
        jMenu6.add(jMenuItem15);

        jMenuItem16.setText("Đổi mật khẩu");
        jMenu6.add(jMenuItem16);

        mniDangXuat.setText("Đăng xuất");
        mniDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangXuatActionPerformed(evt);
            }
        });
        jMenu6.add(mniDangXuat);

        mnuChinh.add(jMenu6);

        setJMenuBar(mnuChinh);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(tabNoiDung, javax.swing.GroupLayout.DEFAULT_SIZE, 1417, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabNoiDung, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniDMNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDMNhanVienActionPerformed

    }//GEN-LAST:event_mniDMNhanVienActionPerformed

    private void mniSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSanPhamActionPerformed
        // TODO add your handling code here:
        qlsp = new FrmQuanLySanPham();
        tabNoiDung.removeAll();
        tabNoiDung.addTab("Quản lý sản phẩm", qlsp);
        tabNoiDung.setSelectedComponent(qlsp);
    }//GEN-LAST:event_mniSanPhamActionPerformed

    private void mniPhanCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPhanCongActionPerformed
        try {
            // TODO add your handling code here:
            pc = new FrmPhanCongCN();
        } catch (Exception ex) {
            Logger.getLogger(TrangChu_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        tabNoiDung.removeAll();
        tabNoiDung.addTab("Phân công", pc);
        tabNoiDung.setSelectedComponent(pc);
    }//GEN-LAST:event_mniPhanCongActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void mniCongNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mniCongNhanMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_mniCongNhanMouseClicked

    private void mniTKNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTKNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniTKNhanVienActionPerformed

    private void mniCongNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCongNhanActionPerformed
        try {
            qlcn = new FrmQuanLyCongNhan();
        } catch (SQLException ex) {
            Logger.getLogger(TrangChu_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        tabNoiDung.removeAll();
        tabNoiDung.addTab("Quản lý công nhân", qlcn);
        tabNoiDung.setSelectedComponent(qlcn);
    }//GEN-LAST:event_mniCongNhanActionPerformed

    private void mniPhanDoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPhanDoanActionPerformed
        // TODO add your handling code here:
        qlcd = new FrmQuanLyPhanDoan();
        tabNoiDung.removeAll();
        tabNoiDung.addTab("Quản lý phân đoạn", qlcd);
        tabNoiDung.setSelectedComponent(qlcd);
    }//GEN-LAST:event_mniPhanDoanActionPerformed

    private void mniTimKiemSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTimKiemSanPhamActionPerformed
        // TODO add your handling code here:
        tksp = new FrmTimKiemSanPham();
        tabNoiDung.removeAll();
        tabNoiDung.addTab("Tìm kiếm sản phẩm", tksp);
        tabNoiDung.setSelectedComponent(tksp);
    }//GEN-LAST:event_mniTimKiemSanPhamActionPerformed

    private void mniTimKiemCongNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTimKiemCongNhanActionPerformed
        // TODO add your handling code here:
        tkcn = new FrmTimKiemCN();
        tabNoiDung.removeAll();
        tabNoiDung.addTab("Tìm kiếm công nhân", tkcn);
        tabNoiDung.setSelectedComponent(tkcn);
    }//GEN-LAST:event_mniTimKiemCongNhanActionPerformed

    private void mniDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangXuatActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(this, "Bạn có muốn đăng xuất không?", "Xác nhận đăng xuất", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_mniDangXuatActionPerformed

    private void mniChamCongCongNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniChamCongCongNhanActionPerformed
        // TODO add your handling code here:
        cccn = new FrmChamCongCN();
        tabNoiDung.removeAll();
        tabNoiDung.addTab("Chấm công công nhân", cccn);
        tabNoiDung.setSelectedComponent(cccn);
    }//GEN-LAST:event_mniChamCongCongNhanActionPerformed

    private void mniThongKeCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniThongKeCNActionPerformed
        // TODO add your handling code here:
        tklcn = new FrmThongKeCN();
        tabNoiDung.removeAll();
        tabNoiDung.addTab("Thống kê lương công nhân", tklcn);
        tabNoiDung.setSelectedComponent(tklcn);
    }//GEN-LAST:event_mniThongKeCNActionPerformed

    private void mniTinhLuongCongNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTinhLuongCongNhanActionPerformed
        // TODO add your handling code here:
        tlcn = new FrmTinhLuongCN();
        tabNoiDung.removeAll();
        tabNoiDung.addTab("Thống kê lương công nhân", tlcn);
        tabNoiDung.setSelectedComponent(tlcn);
    }//GEN-LAST:event_mniTinhLuongCongNhanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChu_GUI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChu_GUI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChu_GUI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu_GUI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {

                new TrangChu_GUI().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JLabel lblTenChuongTrinh;
    private javax.swing.JMenu mnDanhMuc;
    private javax.swing.JMenuItem mniChamCongCongNhan;
    private javax.swing.JMenuItem mniCongNhan;
    private javax.swing.JMenuItem mniDMNhanVien;
    private javax.swing.JMenuItem mniDangXuat;
    private javax.swing.JMenuItem mniPhanCong;
    private javax.swing.JMenuItem mniPhanDoan;
    private javax.swing.JMenuItem mniSanPham;
    private javax.swing.JMenuItem mniTKNhanVien;
    private javax.swing.JMenuItem mniThongKeCN;
    private javax.swing.JMenu mniTimKiem;
    private javax.swing.JMenuItem mniTimKiemCongNhan;
    private javax.swing.JMenuItem mniTimKiemSanPham;
    private javax.swing.JMenuItem mniTinhLuongCongNhan;
    private javax.swing.JMenuBar mnuChinh;
    private javax.swing.JTabbedPane tabNoiDung;
    // End of variables declaration//GEN-END:variables
}
