package gui;

import dao.NhanVienDao;
import entity.NhanVien;
import helper.MaNguoiDung;
import helper.TenNguoiDung;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author huylauri
 */
public class TrangChu_GUI extends javax.swing.JFrame {

    private FrmQuanLyNhanVien frmQuanLyNhanVien;
    private FrmChamCongNhanVien frmChamCongNhanVien;
    private FrmTinhLuongNhanVien frmTinhLuongNhanVien;
    private FrmTimKiemNhanVien frmTimKiemNhanVien;
    private FrmThayDoiMatKhau frmThayDoiMatKhau;

    /*Duy*/
    private FrmQuanLySanPham qlsp;
    private FrmQuanLyPhanDoan qlcd;
    private FrmTimKiemSanPham tksp;
    private FrmTimKiemCongNhan tkcn;
    private FrmChamCongCongNhan cccn;/*Duy*/
    private FrmThongKeCongNhan tklcn;
    private FrmQuanLyCongNhan qlcn;
    private FrmTinhLuongCongNhan tlcn;
    private FrmPhanCongCongNhan pc;
    
    private NhanVienDao nhanVienDao = new NhanVienDao();

    /**
     * Creates new form TrangChu_GUI1
     */
    public TrangChu_GUI(){
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.toBack();
        try {
            khoiTaoThanhMenu();
        } catch (Exception ex) {
            Logger.getLogger(TrangChu_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    private void khoiTaoThanhMenu(){
        try {
            TenNguoiDung nguoiDung = new TenNguoiDung();
            String ten = nguoiDung.getTenNguoiDung();
            mnTaiKhoan.setText(ten);
            
            MaNguoiDung maNguoiDung = new MaNguoiDung();
            String maND = maNguoiDung.getMaNguoiDung();
            NhanVien nv = nhanVienDao.layNVTheoMa(maND);
            if(nv.getPhongBan().getMaPhongBan().equals("PB_KeToan")){
                mnDanhMuc.setVisible(false);                
                mniChamCongCongNhan.setVisible(false);
                mniChamCongNhanVien.setVisible(false);
                mniPhanCong.setVisible(false);
                mniTimKiemSanPham.setVisible(false);
            }else if(nv.getPhongBan().getMaPhongBan().equals("PB_QuanLy")){
                // Mở tất cả menu
            }else{
                mnDanhMuc.setVisible(false);
                mnXuLy.setVisible(false);
                mnTimKiem.setVisible(false);
                mnThongKe.setVisible(false);
            }
        } catch (Exception ex) {
            Logger.getLogger(TrangChu_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabNoiDung = new javax.swing.JTabbedPane();
        lblTenChuongTrinh = new javax.swing.JLabel();
        mnuChinh = new javax.swing.JMenuBar();
        mnTrangChu = new javax.swing.JMenu();
        mnDanhMuc = new javax.swing.JMenu();
        mniDMNhanVien = new javax.swing.JMenuItem();
        mniCongNhan = new javax.swing.JMenuItem();
        mniSanPham = new javax.swing.JMenuItem();
        mniPhanDoan = new javax.swing.JMenuItem();
        mnXuLy = new javax.swing.JMenu();
        mniPhanCong = new javax.swing.JMenuItem();
        mniChamCongNhanVien = new javax.swing.JMenuItem();
        mniChamCongCongNhan = new javax.swing.JMenuItem();
        mniTinhLuongNhanVien = new javax.swing.JMenuItem();
        mniTinhLuongCongNhan = new javax.swing.JMenuItem();
        mnTimKiem = new javax.swing.JMenu();
        mniTKNhanVien = new javax.swing.JMenuItem();
        mniTimKiemCongNhan = new javax.swing.JMenuItem();
        mniTimKiemSanPham = new javax.swing.JMenuItem();
        mnThongKe = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        mniThongKeCN = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        mnTaiKhoan = new javax.swing.JMenu();
        mniDoiMatKhau = new javax.swing.JMenuItem();
        mniDangXuat = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        tabNoiDung.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblTenChuongTrinh.setBackground(new java.awt.Color(255, 255, 204));
        lblTenChuongTrinh.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTenChuongTrinh.setForeground(new java.awt.Color(255, 51, 0));
        lblTenChuongTrinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTenChuongTrinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/anh-trangchu.jpeg"))); // NOI18N
        lblTenChuongTrinh.setText("CHƯƠNG TRÌNH QUẢN LÝ LƯƠNG SẢN PHẨM");
        lblTenChuongTrinh.setToolTipText("");
        lblTenChuongTrinh.setFocusable(false);
        lblTenChuongTrinh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTenChuongTrinh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tabNoiDung.addTab("Trang chính", lblTenChuongTrinh);

        mnuChinh.setToolTipText("");
        mnuChinh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        mnTrangChu.setBackground(new java.awt.Color(0, 0, 0));
        mnTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/home2.png"))); // NOI18N
        mnTrangChu.setText("Trang Chủ");
        mnTrangChu.setFocusable(false);
        mnTrangChu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mnTrangChu.setIconTextGap(0);
        mnTrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnTrangChuMouseClicked(evt);
            }
        });
        mnuChinh.add(mnTrangChu);

        mnDanhMuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icon-danhmuc.png"))); // NOI18N
        mnDanhMuc.setText("Danh mục");
        mnDanhMuc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mnDanhMuc.setIconTextGap(0);

        mniDMNhanVien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mniDMNhanVien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mniDMNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icon-NhanVien2.png"))); // NOI18N
        mniDMNhanVien.setText("Nhân viên");
        mniDMNhanVien.setToolTipText("");
        mniDMNhanVien.setInheritsPopupMenu(true);
        mniDMNhanVien.setPreferredSize(new java.awt.Dimension(220, 36));
        mniDMNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDMNhanVienActionPerformed(evt);
            }
        });
        mnDanhMuc.add(mniDMNhanVien);

        mniCongNhan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mniCongNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icon-CongNhan.png"))); // NOI18N
        mniCongNhan.setText("Công nhân");
        mniCongNhan.setPreferredSize(new java.awt.Dimension(220, 36));
        mniCongNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mniCongNhanMouseClicked(evt);
            }
        });
        mniCongNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCongNhanActionPerformed(evt);
            }
        });
        mnDanhMuc.add(mniCongNhan);

        mniSanPham.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mniSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icon-SanPham.png"))); // NOI18N
        mniSanPham.setText("Sản phẩm");
        mniSanPham.setPreferredSize(new java.awt.Dimension(220, 36));
        mniSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSanPhamActionPerformed(evt);
            }
        });
        mnDanhMuc.add(mniSanPham);

        mniPhanDoan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mniPhanDoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icon-PhanDoan.png"))); // NOI18N
        mniPhanDoan.setText("Phân đoạn");
        mniPhanDoan.setPreferredSize(new java.awt.Dimension(220, 36));
        mniPhanDoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPhanDoanActionPerformed(evt);
            }
        });
        mnDanhMuc.add(mniPhanDoan);

        mnuChinh.add(mnDanhMuc);

        mnXuLy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icon-xuly.png"))); // NOI18N
        mnXuLy.setText("Xử lý");
        mnXuLy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        mniPhanCong.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniPhanCong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mniPhanCong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icon-PhanCong.png"))); // NOI18N
        mniPhanCong.setText("Phân công");
        mniPhanCong.setPreferredSize(new java.awt.Dimension(180, 36));
        mniPhanCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPhanCongActionPerformed(evt);
            }
        });
        mnXuLy.add(mniPhanCong);

        mniChamCongNhanVien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mniChamCongNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icon-chamcongNV.png"))); // NOI18N
        mniChamCongNhanVien.setText("Chấm công nhân viên");
        mniChamCongNhanVien.setPreferredSize(new java.awt.Dimension(198, 36));
        mniChamCongNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniChamCongNhanVienActionPerformed(evt);
            }
        });
        mnXuLy.add(mniChamCongNhanVien);

        mniChamCongCongNhan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mniChamCongCongNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icon-chamcongNV.png"))); // NOI18N
        mniChamCongCongNhan.setText("Chấm công công nhân");
        mniChamCongCongNhan.setPreferredSize(new java.awt.Dimension(220, 36));
        mniChamCongCongNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniChamCongCongNhanActionPerformed(evt);
            }
        });
        mnXuLy.add(mniChamCongCongNhan);

        mniTinhLuongNhanVien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mniTinhLuongNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icon-TinhLuong.png"))); // NOI18N
        mniTinhLuongNhanVien.setText("Tính lương nhân viên");
        mniTinhLuongNhanVien.setPreferredSize(new java.awt.Dimension(180, 36));
        mniTinhLuongNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTinhLuongNhanVienActionPerformed(evt);
            }
        });
        mnXuLy.add(mniTinhLuongNhanVien);

        mniTinhLuongCongNhan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mniTinhLuongCongNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icon-TinhLuong.png"))); // NOI18N
        mniTinhLuongCongNhan.setText("Tính lương công nhân");
        mniTinhLuongCongNhan.setPreferredSize(new java.awt.Dimension(201, 36));
        mniTinhLuongCongNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTinhLuongCongNhanActionPerformed(evt);
            }
        });
        mnXuLy.add(mniTinhLuongCongNhan);

        mnuChinh.add(mnXuLy);

        mnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icon-timkiem0.png"))); // NOI18N
        mnTimKiem.setText("Tìm kiếm");
        mnTimKiem.setAutoscrolls(true);
        mnTimKiem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnTimKiem.setFocusPainted(true);
        mnTimKiem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mnTimKiem.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        mnTimKiem.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        mnTimKiem.setIconTextGap(0);

        mniTKNhanVien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mniTKNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icon-NhanVien2.png"))); // NOI18N
        mniTKNhanVien.setText("Nhân viên");
        mniTKNhanVien.setPreferredSize(new java.awt.Dimension(104, 36));
        mniTKNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTKNhanVienActionPerformed(evt);
            }
        });
        mnTimKiem.add(mniTKNhanVien);

        mniTimKiemCongNhan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mniTimKiemCongNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icon-CongNhan.png"))); // NOI18N
        mniTimKiemCongNhan.setText("Công nhân");
        mniTimKiemCongNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTimKiemCongNhanActionPerformed(evt);
            }
        });
        mnTimKiem.add(mniTimKiemCongNhan);

        mniTimKiemSanPham.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mniTimKiemSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icon-SanPham.png"))); // NOI18N
        mniTimKiemSanPham.setText("Sản phầm");
        mniTimKiemSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTimKiemSanPhamActionPerformed(evt);
            }
        });
        mnTimKiem.add(mniTimKiemSanPham);

        mnuChinh.add(mnTimKiem);

        mnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icon-thongke.png"))); // NOI18N
        mnThongKe.setText("Thống Kê");
        mnThongKe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mnThongKe.setIconTextGap(0);

        jMenuItem12.setText("Tiền lương");
        mnThongKe.add(jMenuItem12);

        jMenuItem13.setText("Sản phẩm");
        mnThongKe.add(jMenuItem13);

        jMenuItem14.setText("Xuất phiếu lương");
        mnThongKe.add(jMenuItem14);

        mniThongKeCN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mniThongKeCN.setText("Công nhân");
        mniThongKeCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniThongKeCNActionPerformed(evt);
            }
        });
        mnThongKe.add(mniThongKeCN);

        jMenuItem2.setText("Nhân viên");
        mnThongKe.add(jMenuItem2);

        mnuChinh.add(mnThongKe);

        mnTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icon-taikhoan.png"))); // NOI18N
        mnTaiKhoan.setText("Tài Khoản");
        mnTaiKhoan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mnTaiKhoan.setIconTextGap(4);

        mniDoiMatKhau.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mniDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icon-DoiMatKhau.png"))); // NOI18N
        mniDoiMatKhau.setText("Đổi mật khẩu");
        mniDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDoiMatKhauActionPerformed(evt);
            }
        });
        mnTaiKhoan.add(mniDoiMatKhau);

        mniDangXuat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mniDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icon-DangXuat.png"))); // NOI18N
        mniDangXuat.setText("Đăng xuất");
        mniDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangXuatActionPerformed(evt);
            }
        });
        mnTaiKhoan.add(mniDangXuat);

        mnuChinh.add(mnTaiKhoan);

        setJMenuBar(mnuChinh);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(tabNoiDung, javax.swing.GroupLayout.DEFAULT_SIZE, 1417, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabNoiDung, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniDMNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDMNhanVienActionPerformed
        // TODO add your handling code here
        frmQuanLyNhanVien = new FrmQuanLyNhanVien();
        tabNoiDung.removeAll();
        tabNoiDung.addTab("Trang chủ", lblTenChuongTrinh);
        tabNoiDung.addTab("Quản lý nhân viên", frmQuanLyNhanVien);
        tabNoiDung.setSelectedComponent(frmQuanLyNhanVien);
    }//GEN-LAST:event_mniDMNhanVienActionPerformed

    private void mniSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSanPhamActionPerformed
        try {
            qlsp = new FrmQuanLySanPham();
        } catch (Exception ex) {
            Logger.getLogger(TrangChu_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        tabNoiDung.removeAll();
        tabNoiDung.addTab("Quản lý sản phẩm", qlsp);
        tabNoiDung.setSelectedComponent(qlsp);
    }//GEN-LAST:event_mniSanPhamActionPerformed

    private void mniTinhLuongNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTinhLuongNhanVienActionPerformed
        frmTinhLuongNhanVien = new FrmTinhLuongNhanVien();
        tabNoiDung.removeAll();
        tabNoiDung.addTab("Trang chủ", lblTenChuongTrinh);
        tabNoiDung.addTab("Tính lương nhân viên", frmTinhLuongNhanVien);
        tabNoiDung.setSelectedComponent(frmTinhLuongNhanVien);
    }//GEN-LAST:event_mniTinhLuongNhanVienActionPerformed

    private void mniCongNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mniCongNhanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mniCongNhanMouseClicked

    private void mniTKNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTKNhanVienActionPerformed
        frmTimKiemNhanVien = new FrmTimKiemNhanVien();
        tabNoiDung.removeAll();
        tabNoiDung.addTab("Trang chủ", lblTenChuongTrinh);
        tabNoiDung.addTab("Tìm kiếm nhân viên", frmTimKiemNhanVien);
        tabNoiDung.setSelectedComponent(frmTimKiemNhanVien);
    }//GEN-LAST:event_mniTKNhanVienActionPerformed

    private void mnTrangChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnTrangChuMouseClicked
        tabNoiDung.removeAll();
        tabNoiDung.addTab("Trang chủ", lblTenChuongTrinh);
    }//GEN-LAST:event_mnTrangChuMouseClicked

    private void mniCongNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCongNhanActionPerformed
        try {
            qlcn = new FrmQuanLyCongNhan();
        } catch (SQLException ex) {
            Logger.getLogger(TrangChu_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        tabNoiDung.removeAll();
        tabNoiDung.addTab("Quản lý công nhân", qlcn);
        tabNoiDung.setSelectedComponent(qlcn);
    }//GEN-LAST:event_mniCongNhanActionPerformed

    private void mniPhanDoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPhanDoanActionPerformed
        try {
            qlcd = new FrmQuanLyPhanDoan();
        } catch (Exception ex) {
            Logger.getLogger(TrangChu_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        tabNoiDung.removeAll();
        tabNoiDung.addTab("Quản lý phân đoạn", qlcd);
        tabNoiDung.setSelectedComponent(qlcd);
    }//GEN-LAST:event_mniPhanDoanActionPerformed

    private void mniPhanCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPhanCongActionPerformed
        try {
            // TODO add your handling code here:
            pc = new FrmPhanCongCongNhan();
        } catch (Exception ex) {
            Logger.getLogger(TrangChu_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        tabNoiDung.removeAll();
        tabNoiDung.addTab("Phân công", pc);
        tabNoiDung.setSelectedComponent(pc);
    }//GEN-LAST:event_mniPhanCongActionPerformed

    private void mniChamCongCongNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniChamCongCongNhanActionPerformed
        try {
            cccn = new FrmChamCongCongNhan();
        } catch (Exception ex) {
            Logger.getLogger(TrangChu_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        tabNoiDung.removeAll();
        tabNoiDung.addTab("Chấm công công nhân", cccn);
        tabNoiDung.setSelectedComponent(cccn);
    }//GEN-LAST:event_mniChamCongCongNhanActionPerformed

    private void mniTinhLuongCongNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTinhLuongCongNhanActionPerformed
        tlcn = new FrmTinhLuongCongNhan();
        tabNoiDung.removeAll();
        tabNoiDung.addTab("Thống kê lương công nhân", tlcn);
        tabNoiDung.setSelectedComponent(tlcn);
    }//GEN-LAST:event_mniTinhLuongCongNhanActionPerformed

    private void mniTimKiemCongNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTimKiemCongNhanActionPerformed
        tkcn = new FrmTimKiemCongNhan();
        tabNoiDung.removeAll();
        tabNoiDung.addTab("Tìm kiếm công nhân", tkcn);
        tabNoiDung.setSelectedComponent(tkcn);
    }//GEN-LAST:event_mniTimKiemCongNhanActionPerformed

    private void mniTimKiemSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTimKiemSanPhamActionPerformed
        tksp = new FrmTimKiemSanPham();
        tabNoiDung.removeAll();
        tabNoiDung.addTab("Tìm kiếm sản phẩm", tksp);
        tabNoiDung.setSelectedComponent(tksp);
    }//GEN-LAST:event_mniTimKiemSanPhamActionPerformed

    private void mniThongKeCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniThongKeCNActionPerformed
        tklcn = new FrmThongKeCongNhan();
        tabNoiDung.removeAll();
        tabNoiDung.addTab("Thống kê lương công nhân", tklcn);
        tabNoiDung.setSelectedComponent(tklcn);
    }//GEN-LAST:event_mniThongKeCNActionPerformed

    private void mniDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangXuatActionPerformed
        this.dispose();
        FrmDangNhapDangKy frmDangNhapDangKy = new FrmDangNhapDangKy();
        frmDangNhapDangKy.setVisible(true);
    }//GEN-LAST:event_mniDangXuatActionPerformed

    private void mniDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoiMatKhauActionPerformed
        frmThayDoiMatKhau = new FrmThayDoiMatKhau();
        tabNoiDung.removeAll();
        tabNoiDung.addTab("Trang chủ", lblTenChuongTrinh);
        tabNoiDung.addTab("Thay đổi mật khẩu", frmThayDoiMatKhau);
        tabNoiDung.setSelectedComponent(frmThayDoiMatKhau);
    }//GEN-LAST:event_mniDoiMatKhauActionPerformed

    private void mniChamCongNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniChamCongNhanVienActionPerformed
        frmChamCongNhanVien = new FrmChamCongNhanVien();
        tabNoiDung.removeAll();
        tabNoiDung.addTab("Trang chủ", lblTenChuongTrinh);
        tabNoiDung.addTab("Chấm công nhân viên", frmChamCongNhanVien);
        tabNoiDung.setSelectedComponent(frmChamCongNhanVien);
    }//GEN-LAST:event_mniChamCongNhanVienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TrangChu_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel lblTenChuongTrinh;
    private javax.swing.JMenu mnDanhMuc;
    private javax.swing.JMenu mnTaiKhoan;
    private javax.swing.JMenu mnThongKe;
    private javax.swing.JMenu mnTimKiem;
    private javax.swing.JMenu mnTrangChu;
    private javax.swing.JMenu mnXuLy;
    private javax.swing.JMenuItem mniChamCongCongNhan;
    private javax.swing.JMenuItem mniChamCongNhanVien;
    private javax.swing.JMenuItem mniCongNhan;
    private javax.swing.JMenuItem mniDMNhanVien;
    private javax.swing.JMenuItem mniDangXuat;
    private javax.swing.JMenuItem mniDoiMatKhau;
    private javax.swing.JMenuItem mniPhanCong;
    private javax.swing.JMenuItem mniPhanDoan;
    private javax.swing.JMenuItem mniSanPham;
    private javax.swing.JMenuItem mniTKNhanVien;
    private javax.swing.JMenuItem mniThongKeCN;
    private javax.swing.JMenuItem mniTimKiemCongNhan;
    private javax.swing.JMenuItem mniTimKiemSanPham;
    private javax.swing.JMenuItem mniTinhLuongCongNhan;
    private javax.swing.JMenuItem mniTinhLuongNhanVien;
    private javax.swing.JMenuBar mnuChinh;
    private javax.swing.JTabbedPane tabNoiDung;
    // End of variables declaration//GEN-END:variables
}
